<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.26">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Xiran Yin">
<meta name="dcterms.date" content="2026-04-26">

<title>Predicting TTC Subway Delays from Weather Data – Weather &amp; TTC Delays — JSC370 Final Project</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-587c61ba64f3a5504c4d52d930310e48.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-f245066ca199b7326ac6b360085ddf3a.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Weather &amp; TTC Delays — JSC370 Final Project</span>
    </a>
  </div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="./final_report.html" aria-current="page"> 
<span class="menu-text">Full Report</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./viz.html"> 
<span class="menu-text">Interactive Visualizations</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./final_report.pdf"> 
<span class="menu-text">Download PDF</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://github.com/xiran-yin/JSC370-finalproject"> 
<span class="menu-text">GitHub</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction"><span class="header-section-number">1</span> Introduction</a>
  <ul class="collapse">
  <li><a href="#central-research-question" id="toc-central-research-question" class="nav-link" data-scroll-target="#central-research-question"><span class="header-section-number">1.1</span> Central Research Question</a></li>
  </ul></li>
  <li><a href="#methods" id="toc-methods" class="nav-link" data-scroll-target="#methods"><span class="header-section-number">2</span> Methods</a>
  <ul class="collapse">
  <li><a href="#data-sources" id="toc-data-sources" class="nav-link" data-scroll-target="#data-sources"><span class="header-section-number">2.1</span> Data Sources</a></li>
  <li><a href="#data-acquisition-and-cleaning" id="toc-data-acquisition-and-cleaning" class="nav-link" data-scroll-target="#data-acquisition-and-cleaning"><span class="header-section-number">2.2</span> Data Acquisition and Cleaning</a></li>
  <li><a href="#statistical-and-machine-learning-methods" id="toc-statistical-and-machine-learning-methods" class="nav-link" data-scroll-target="#statistical-and-machine-learning-methods"><span class="header-section-number">2.3</span> Statistical and Machine-Learning Methods</a></li>
  </ul></li>
  <li><a href="#results" id="toc-results" class="nav-link" data-scroll-target="#results"><span class="header-section-number">3</span> Results</a>
  <ul class="collapse">
  <li><a href="#descriptive-statistics" id="toc-descriptive-statistics" class="nav-link" data-scroll-target="#descriptive-statistics"><span class="header-section-number">3.1</span> Descriptive Statistics</a></li>
  <li><a href="#h₁-explanatory-models" id="toc-h₁-explanatory-models" class="nav-link" data-scroll-target="#h₁-explanatory-models"><span class="header-section-number">3.2</span> H₁ — Explanatory Models</a></li>
  <li><a href="#h₂-predictive-models" id="toc-h₂-predictive-models" class="nav-link" data-scroll-target="#h₂-predictive-models"><span class="header-section-number">3.3</span> H₂ — Predictive Models</a></li>
  </ul></li>
  <li><a href="#conclusions-and-summary" id="toc-conclusions-and-summary" class="nav-link" data-scroll-target="#conclusions-and-summary"><span class="header-section-number">4</span> Conclusions and Summary</a>
  <ul class="collapse">
  <li><a href="#note-on-detrending-and-distribution-shift" id="toc-note-on-detrending-and-distribution-shift" class="nav-link" data-scroll-target="#note-on-detrending-and-distribution-shift"><span class="header-section-number">4.1</span> Note on Detrending and Distribution Shift</a></li>
  <li><a href="#limitations" id="toc-limitations" class="nav-link" data-scroll-target="#limitations"><span class="header-section-number">4.2</span> Limitations</a></li>
  </ul></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="final_report.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title">Predicting TTC Subway Delays from Weather Data</h1><button type="button" class="btn code-tools-button" id="quarto-code-tools-source"><i class="bi"></i> Code</button></div></div>
<p class="subtitle lead">JSC370 Final Project Report</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Xiran Yin </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">April 26, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="introduction" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Introduction</h1>
<p>The Toronto Transit Commission (TTC) carries over one million riders per day, making subway reliability a substantial piece of urban infrastructure. While many causes of delay — equipment failures, passenger incidents, security investigations — are random from a forecasting perspective, <strong>weather</strong> is one of the few systematic, externally observable, and forecastable variables that plausibly drives day-to-day delay patterns. Cold snaps freeze track switches; heavy snow buries third rails; extreme heat causes rail steel to expand. This project asks whether daily Toronto weather predicts TTC delays, by integrating 12 years of meteorological observations (2014–2025) with the City of Toronto’s complete public record of subway delays.</p>
<section id="central-research-question" class="level2" data-number="1.1">
<h2 data-number="1.1" class="anchored" data-anchor-id="central-research-question"><span class="header-section-number">1.1</span> Central Research Question</h2>
<blockquote class="blockquote">
<p><strong>Can daily weather conditions predict TTC subway delays, and if so, which weather features matter most — both for explaining day-to-day variation and for forecasting severe delay days?</strong></p>
</blockquote>
<p>The question has two halves: an <em>explanatory</em> half (which weather variables associate with delay, and how?) and a <em>predictive</em> half (can that association be turned into a forecasting tool?). Each maps to a formal hypothesis with an explicit null.</p>
<p><strong>H₁ — Explanatory.</strong> Adverse weather is associated with longer total daily delays, with potentially non-linear functional form. <em>Null:</em> the partial slopes on precipitation and snowfall are zero, and the smooths are flat, after controlling for month and day-of-week. <em>Alternative:</em> slopes are positive; smooths exhibit non-linear structure (e.g., U-shaped temperature). H₁ is tested with OLS and a Generalized Additive Model (GAM).</p>
<p><strong>H₂ — Predictive.</strong> A supervised ML model trained on weather and temporal features outperforms a no-information baseline. <em>Null:</em> out-of-sample R² ≤ 0 and ROC-AUC ≤ 0.5. <em>Alternative:</em> R² &gt; 0 and ROC-AUC &gt; 0.5 on a chronologically held-out test set. H₂ is tested by training Linear/Logistic Regression, Random Forest, and XGBoost on 2014–2023 data and evaluating on 2024–2025.</p>
<p>GitHub repo: <a href="https://github.com/xiran-yin/JSC370-finalproject" class="uri">https://github.com/xiran-yin/JSC370-finalproject</a>.</p>
</section>
</section>
<section id="methods" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Methods</h1>
<section id="data-sources" class="level2" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="data-sources"><span class="header-section-number">2.1</span> Data Sources</h2>
<p>Two independent sources are combined: (1) <strong>Weather</strong> — <a href="https://open-meteo.com/en/docs/historical-weather-api">Open-Meteo Historical Weather API</a>, Toronto (43.7064°N, −79.3986°W), daily aggregates 2014–2026; (2) <strong>TTC delays</strong> — City of Toronto Open Data Portal <a href="https://open.toronto.ca/dataset/ttc-subway-delay-data/"><code>ttc-subway-delay-data</code></a>, every recorded incident 2014–2025, retrieved via the CKAN API.</p>
</section>
<section id="data-acquisition-and-cleaning" class="level2" data-number="2.2">
<h2 data-number="2.2" class="anchored" data-anchor-id="data-acquisition-and-cleaning"><span class="header-section-number">2.2</span> Data Acquisition and Cleaning</h2>
<p>Weather acquisition is one HTTPS GET to the Open-Meteo archive. TTC acquisition handles three obstacles: (i) <strong>format dispatching</strong> (mixed CSV/XLSX requires different pandas readers); (ii) <strong>multi-sheet Excel</strong> (2014–2017 files split records across 12 monthly worksheets — <code>sheet_name=None</code> is required to avoid silently dropping ~92% of those years); (iii) <strong>inconsistent column names</strong> (“Date” / “Occurrence Date”; “Min Delay” / “min_delay”) — handled by substring-matching against known synonyms.</p>
<p>The merged dataset has <strong>4,384 daily observations</strong>. A three-level <strong>categorical weather severity variable</strong> is derived using two fixed breakpoints — <code>precip_mm ≥ 10</code> <em>or</em> <code>snowfall_cm ≥ 5</code> for “Heavy”, either positive but neither at threshold for “Light”, otherwise “Clear” — corresponding to Environment Canada’s heavy-rain advisory level. Because the TTC has experienced a structural rise in delays since 2021 (mean total daily delay rose from ~113 min/day in 2014 to ~200 min/day by 2022), we <strong>detrend</strong> the predictive target by subtracting each day’s calendar-month mean. The detrended target <code>delay_anomaly</code> represents how much worse (or better) a given day was than typical for that month, isolating weather-driven variation from baseline drift. The binary classification target <code>is_severe</code> flags days at or above the <strong>training-period</strong> 75th percentile of <code>delay_anomaly</code>, so that “severe” means the same thing across the 12-year window.</p>
</section>
<section id="statistical-and-machine-learning-methods" class="level2" data-number="2.3">
<h2 data-number="2.3" class="anchored" data-anchor-id="statistical-and-machine-learning-methods"><span class="header-section-number">2.3</span> Statistical and Machine-Learning Methods</h2>
<p><strong>Inferential</strong> (testing H₁): (i) <strong>OLS multiple regression</strong> of <code>total_delay_mins</code> on precipitation, snowfall, gust speed, mean temperature, weekend, and month fixed effects, as a linear baseline. (ii) <strong>GAM</strong> via <code>pygam.LinearGAM(s(precip) + s(temp) + f(weekend) + f(month))</code>, with 20-knot penalized cubic splines and smoothing parameters chosen by generalized cross-validation, to capture non-linearity.</p>
<p><strong>Predictive</strong> (testing H₂): three supervised models fit twice — once for regression (target: <code>delay_anomaly</code>) and once for classification (target: <code>is_severe</code>). The models are <strong>Linear/Logistic Regression</strong> (baseline), <strong>Random Forest</strong> (<code>sklearn.ensemble</code>), and <strong>XGBoost</strong> (<code>xgboost</code>). Hyperparameters: RF — <code>n_estimators=300–400</code>, <code>max_depth=8–10</code>; XGBoost — <code>n_estimators=400</code>, <code>max_depth=6</code>, <code>learning_rate=0.05</code>, <code>subsample=0.8</code>. Twelve features are used: <code>precip_mm</code>, <code>snowfall_cm</code>, <code>precip_hours</code>, <code>precip_intensity</code>, <code>temp_max</code>, <code>temp_min</code>, <code>mean_temp_c</code>, <code>temp_range</code>, <code>gust_speed</code>, <code>is_weekend</code>, <code>month_num</code>, <code>dow_num</code>. The data are split <strong>chronologically</strong> — train on 2014-01-01 to 2023-12-31, test on 2024-01-01 onward — to prevent the model from learning future information. Regression metrics: RMSE, MAE, R². Classification metrics: accuracy, precision, recall, F1, ROC-AUC.</p>
</section>
</section>
<section id="results" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Results</h1>
<section id="descriptive-statistics" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="descriptive-statistics"><span class="header-section-number">3.1</span> Descriptive Statistics</h2>
<div class="cell" data-execution_count="5">
<div id="tbl-summary" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="5">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl quarto-uncaptioned" id="tbl-summary-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1
</figcaption>
<div aria-describedby="tbl-summary-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display cell-output-markdown">
<p><strong>Table 1.</strong> Descriptive statistics, 2014–2025.</p>
<table class="do-not-create-environment caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">N</th>
<th style="text-align: right;">Mean</th>
<th style="text-align: right;">SD</th>
<th style="text-align: right;">Min</th>
<th style="text-align: right;">Median</th>
<th style="text-align: right;">Max</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Total Delay (min)</td>
<td style="text-align: right;">4384</td>
<td style="text-align: right;">144.3</td>
<td style="text-align: right;">96.9</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">123</td>
<td style="text-align: right;">2342</td>
</tr>
<tr class="even">
<td style="text-align: left;">Total Incidents</td>
<td style="text-align: right;">4384</td>
<td style="text-align: right;">56.6</td>
<td style="text-align: right;">16.2</td>
<td style="text-align: right;">15</td>
<td style="text-align: right;">56</td>
<td style="text-align: right;">144</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Mean Temp (°C)</td>
<td style="text-align: right;">4384</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">10.2</td>
<td style="text-align: right;">-21.3</td>
<td style="text-align: right;">8.8</td>
<td style="text-align: right;">31.4</td>
</tr>
<tr class="even">
<td style="text-align: left;">Precip (mm)</td>
<td style="text-align: right;">4384</td>
<td style="text-align: right;">2.4</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.1</td>
<td style="text-align: right;">48</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Snowfall (cm)</td>
<td style="text-align: right;">4384</td>
<td style="text-align: right;">0.2</td>
<td style="text-align: right;">1.1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">24.6</td>
</tr>
<tr class="even">
<td style="text-align: left;">Gust Speed (km/h)</td>
<td style="text-align: right;">4384</td>
<td style="text-align: right;">41.9</td>
<td style="text-align: right;">12.8</td>
<td style="text-align: right;">13.7</td>
<td style="text-align: right;">40.3</td>
<td style="text-align: right;">119.9</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<div class="cell" data-execution_count="6">
<div id="tbl-weather" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="6">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl quarto-uncaptioned" id="tbl-weather-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2
</figcaption>
<div aria-describedby="tbl-weather-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display cell-output-markdown">
<p><strong>Table 2.</strong> Mean delay by weather category.</p>
<table class="do-not-create-environment caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 23%">
<col style="width: 16%">
<col style="width: 27%">
<col style="width: 9%">
<col style="width: 22%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Weather Type</th>
<th style="text-align: right;">N (days)</th>
<th style="text-align: right;">Mean Delay (min)</th>
<th style="text-align: right;">SD</th>
<th style="text-align: right;">Median (min)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Clear</td>
<td style="text-align: right;">1937</td>
<td style="text-align: right;">136.5</td>
<td style="text-align: right;">84.7</td>
<td style="text-align: right;">119</td>
</tr>
<tr class="even">
<td style="text-align: left;">Light Rain/Snow</td>
<td style="text-align: right;">2102</td>
<td style="text-align: right;">145.9</td>
<td style="text-align: right;">88.1</td>
<td style="text-align: right;">126</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Heavy Rain/Snow</td>
<td style="text-align: right;">345</td>
<td style="text-align: right;">178.7</td>
<td style="text-align: right;">174</td>
<td style="text-align: right;">139</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>System-wide total delay averages 144 min/day with a heavy right tail. Mean total delay rises monotonically from Clear (~137 min) to Light (~146 min) to Heavy (~179 min), consistent with severe events triggering disproportionate disruption.</p>
</section>
<section id="h₁-explanatory-models" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="h₁-explanatory-models"><span class="header-section-number">3.2</span> H₁ — Explanatory Models</h2>
<div id="cell-ols" class="cell" data-execution_count="7">
<div id="ols" class="cell-output cell-output-display cell-output-markdown">
<p><strong>Table 3.</strong> OLS regression of total daily delay. R² = 0.067. Month FE included.</p>
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Predictor</th>
<th style="text-align: right;">Coef</th>
<th style="text-align: right;">SE</th>
<th style="text-align: right;">t</th>
<th style="text-align: left;">p</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Precipitation (mm)</td>
<td style="text-align: right;">1.213</td>
<td style="text-align: right;">0.319</td>
<td style="text-align: right;">3.8</td>
<td style="text-align: left;">0.0001</td>
</tr>
<tr class="even">
<td style="text-align: left;">Snowfall (cm)</td>
<td style="text-align: right;">14.264</td>
<td style="text-align: right;">1.422</td>
<td style="text-align: right;">10.03</td>
<td style="text-align: left;">&lt;0.001</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Gust Speed (km/h)</td>
<td style="text-align: right;">-0.125</td>
<td style="text-align: right;">0.119</td>
<td style="text-align: right;">-1.05</td>
<td style="text-align: left;">0.2933</td>
</tr>
<tr class="even">
<td style="text-align: left;">Mean Temp (°C)</td>
<td style="text-align: right;">0.024</td>
<td style="text-align: right;">0.338</td>
<td style="text-align: right;">0.07</td>
<td style="text-align: left;">0.9425</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Weekend (indicator)</td>
<td style="text-align: right;">-32.233</td>
<td style="text-align: right;">3.135</td>
<td style="text-align: right;">-10.28</td>
<td style="text-align: left;">&lt;0.001</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>OLS shows three results. (i) <strong>Precipitation and snowfall are both significant positive predictors</strong>; snowfall’s per-unit effect (~14 min/cm) is roughly <strong>10× larger</strong> than rain’s (~1.2 min/mm) — frozen precipitation is operationally far more disruptive. (ii) <strong>Weekends lose ~32 fewer minutes</strong> to delay than weather-matched weekdays. (iii) <strong>Mean temperature is non-significant</strong> linearly — an artifact, since the GAM below shows a U-shape that a single linear coefficient cannot capture.</p>
<div id="cell-fig-gam" class="cell" data-execution_count="9">
<div class="cell-output cell-output-display" data-execution_count="9">
<div id="fig-gam" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-gam-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="final_report_files/figure-html/fig-gam-output-1.svg" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-gam-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: <strong>Figure 1.</strong> GAM partial-dependence smooth for mean daily temperature. The U-shape — predicted delay minimized in 5–20°C and rising at both extremes — is consistent with frozen track switches in winter and rail thermal expansion in summer.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The GAM (pseudo-R² = 0.063) <strong>rejects H₁₀</strong>. Two non-linearities OLS cannot capture: (a) <strong>temperature is U-shaped</strong> (Figure 1); (b) the precipitation smooth saturates near ~10 mm — its right-edge downturn beyond ~15 mm is an extrapolation artifact in a sparse data region, not real saturation. Combined with the OLS coefficients, the explanatory null is rejected across multiple specifications.</p>
</section>
<section id="h₂-predictive-models" class="level2" data-number="3.3">
<h2 data-number="3.3" class="anchored" data-anchor-id="h₂-predictive-models"><span class="header-section-number">3.3</span> H₂ — Predictive Models</h2>
<div class="cell" data-execution_count="11">
<div id="tbl-reg" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="11">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl quarto-uncaptioned" id="tbl-reg-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;3
</figcaption>
<div aria-describedby="tbl-reg-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display cell-output-markdown">
<p><strong>Table 4.</strong> Out-of-sample regression performance on the detrended target (<code>delay_anomaly</code>), test 2024–2025. RMSE/MAE in min.</p>
<table class="do-not-create-environment caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">RMSE</th>
<th style="text-align: right;">MAE</th>
<th style="text-align: right;">R²</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Naive (mean)</td>
<td style="text-align: right;">117.8</td>
<td style="text-align: right;">64.73</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Linear Regression</td>
<td style="text-align: right;">113.526</td>
<td style="text-align: right;">62.629</td>
<td style="text-align: right;">0.071</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Random Forest</td>
<td style="text-align: right;">114.975</td>
<td style="text-align: right;">63.106</td>
<td style="text-align: right;">0.047</td>
</tr>
<tr class="even">
<td style="text-align: left;">XGBoost</td>
<td style="text-align: right;">113.189</td>
<td style="text-align: right;">66.015</td>
<td style="text-align: right;">0.077</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<div class="cell" data-execution_count="12">
<div id="tbl-clf" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="12">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl quarto-uncaptioned" id="tbl-clf-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;4
</figcaption>
<div aria-describedby="tbl-clf-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display cell-output-markdown">
<p><strong>Table 5.</strong> Out-of-sample classification performance, test 2024–2025. Severe = top-quartile detrended anomaly.</p>
<table class="do-not-create-environment caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 28%">
<col style="width: 16%">
<col style="width: 17%">
<col style="width: 13%">
<col style="width: 9%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">Accuracy</th>
<th style="text-align: right;">Precision</th>
<th style="text-align: right;">Recall</th>
<th style="text-align: right;">F1</th>
<th style="text-align: right;">ROC-AUC</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Logistic Regression</td>
<td style="text-align: right;">0.708</td>
<td style="text-align: right;">0.5</td>
<td style="text-align: right;">0.005</td>
<td style="text-align: right;">0.009</td>
<td style="text-align: right;">0.603</td>
</tr>
<tr class="even">
<td style="text-align: left;">Random Forest</td>
<td style="text-align: right;">0.702</td>
<td style="text-align: right;">0.25</td>
<td style="text-align: right;">0.009</td>
<td style="text-align: right;">0.018</td>
<td style="text-align: right;">0.589</td>
</tr>
<tr class="odd">
<td style="text-align: left;">XGBoost</td>
<td style="text-align: right;">0.669</td>
<td style="text-align: right;">0.241</td>
<td style="text-align: right;">0.061</td>
<td style="text-align: right;">0.097</td>
<td style="text-align: right;">0.538</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<div id="cell-fig-roc" class="cell" data-execution_count="13">
<div class="cell-output cell-output-display">
<div id="fig-roc" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-roc-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="final_report_files/figure-html/fig-roc-output-1.svg" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-roc-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: <strong>Figure 2.</strong> ROC curves on the held-out 2024–2025 test set, predicting top-quartile severe delay days. The dashed diagonal is the no-information baseline (AUC = 0.5).
</figcaption>
</figure>
</div>
</div>
</div>
<div id="cell-fig-fi" class="cell" data-execution_count="14">
<div class="cell-output cell-output-display">
<div id="fig-fi" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-fi-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="final_report_files/figure-html/fig-fi-output-1.svg" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-fi-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: <strong>Figure 3.</strong> XGBoost regressor feature importance (gain). Top three (red): snowfall, mean temperature, day-of-week — matching the predictors flagged as most consequential by OLS and GAM.
</figcaption>
</figure>
</div>
</div>
</div>
<p>After detrending, <strong>XGBoost achieves the best out-of-sample performance</strong> for both tasks (regression: RMSE = 113.2 min, R² = 0.077; classification: ROC-AUC = 0.538). Random Forest is close behind; linear models lag substantially. All three classifiers clear the 0.5 baseline, so <strong>H₂₀ is rejected</strong>. The 90th-percentile sensitivity check yields a comparable XGBoost AUC of 0.581, confirming robustness to the cutoff choice. The R² is modest in absolute terms, as expected — most large single-day delays are caused by random non-weather events (signal failures, security incidents) unforecastable from weather alone. The <strong>top three features by gain — snowfall, mean temperature, day-of-week</strong> (Figure 3) — match the OLS and GAM findings, providing convergent evidence across linear, spline-based, and tree-based model classes.</p>
</section>
</section>
<section id="conclusions-and-summary" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Conclusions and Summary</h1>
<p><strong>H₁ — Explanatory (rejected the null).</strong> OLS finds precipitation (β ≈ 1.2 min/mm, p &lt; 0.001) and snowfall (β ≈ 14 min/cm, p &lt; 0.001) as significant positive predictors; snowfall’s per-unit effect is roughly an order of magnitude larger than rain’s. The GAM further reveals a <strong>U-shaped temperature effect</strong> — predicted delay minimized 5–20°C and rising at both extremes — that OLS could not capture. The weekend indicator is strongly negative (β ≈ −32 min, p &lt; 0.001).</p>
<p><strong>H₂ — Predictive (rejected the null).</strong> After detrending the target to remove the post-2021 baseline rise, <strong>XGBoost achieves the best out-of-sample performance</strong> for both regression (RMSE ≈ 113 min, R² ≈ 0.08) and classification (ROC-AUC ≈ 0.54). All three models clear the no-information baselines, and the 90th-percentile sensitivity check confirms the conclusion does not depend on the cutoff. Most importantly, the <strong>top three features by gain — snowfall, mean temperature, day-of-week</strong> — match the predictors that OLS and GAM identified as most consequential, demonstrating convergence between explanatory and predictive analyses across very different model classes.</p>
<section id="note-on-detrending-and-distribution-shift" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="note-on-detrending-and-distribution-shift"><span class="header-section-number">4.1</span> Note on Detrending and Distribution Shift</h2>
<p>A direct prediction of <code>total_delay_mins</code> produces <em>negative</em> out-of-sample R² for all three models — not because weather lacks predictive signal, but because the test-period mean total delay (~200 min) is far above the training-period mean (~140 min), so any model anchored to the training distribution systematically under-predicts. By predicting <code>delay_anomaly</code> (each day’s deviation from its calendar-month mean) we remove this baseline drift and isolate the weather-driven component. This is the methodologically appropriate approach when the target series is non-stationary, as is the case for TTC delays after 2021.</p>
</section>
<section id="limitations" class="level2" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="limitations"><span class="header-section-number">4.2</span> Limitations</h2>
<ol type="1">
<li><strong>Weather explains a modest fraction of variance.</strong> Even after detrending, XGBoost achieves only R² ≈ 0.08. Most day-to-day variation in delay anomalies is driven by non-weather factors (equipment failures, security incidents, passenger emergencies) the data do not capture. Operational data (rolling-stock age, ridership) at daily granularity would likely improve performance but is not publicly available. (2) <strong>Aggregation hides line-level heterogeneity.</strong> Different lines have different vulnerabilities — Line 1 (mostly underground) is largely insulated from snow, while at-grade segments are far more weather-sensitive. Line/station disaggregation is a natural next step. (3) <strong>Production deployment requires re-training.</strong> The post-2021 baseline rise documented here means a model trained on historical data cannot be deployed indefinitely; annual or quarterly re-training would be needed to track the drifting baseline.</li>
</ol>


<!-- -->

</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
    const viewSource = window.document.getElementById('quarto-view-source') ||
                       window.document.getElementById('quarto-code-tools-source');
    if (viewSource) {
      const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
      viewSource.addEventListener("click", function(e) {
        if (sourceUrl) {
          // rstudio viewer pane
          if (/\bcapabilities=\b/.test(window.location)) {
            window.open(sourceUrl);
          } else {
            window.location.href = sourceUrl;
          }
        } else {
          const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
          modal.show();
        }
        return false;
      });
    }
    function toggleCodeHandler(show) {
      return function(e) {
        const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
        for (let i=0; i<detailsSrc.length; i++) {
          const details = detailsSrc[i].parentElement;
          if (show) {
            details.open = true;
          } else {
            details.removeAttribute("open");
          }
        }
        const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
        const fromCls = show ? "hidden" : "unhidden";
        const toCls = show ? "unhidden" : "hidden";
        for (let i=0; i<cellCodeDivs.length; i++) {
          const codeDiv = cellCodeDivs[i];
          if (codeDiv.classList.contains(fromCls)) {
            codeDiv.classList.remove(fromCls);
            codeDiv.classList.add(toCls);
          } 
        }
        return false;
      }
    }
    const hideAllCode = window.document.getElementById("quarto-hide-all-code");
    if (hideAllCode) {
      hideAllCode.addEventListener("click", toggleCodeHandler(false));
    }
    const showAllCode = window.document.getElementById("quarto-show-all-code");
    if (showAllCode) {
      showAllCode.addEventListener("click", toggleCodeHandler(true));
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "Predicting TTC Subway Delays from Weather Data"</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="an">subtitle:</span><span class="co"> "JSC370 Final Project Report"</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="an">author:</span><span class="co"> "Xiran Yin"</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="an">date:</span><span class="co"> "April 26, 2026"</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="an">format:</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="co">  html:</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="co">    toc: true</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="co">    toc-depth: 3</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="co">    number-sections: true</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="co">    code-fold: true</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="co">    fig-format: svg</span></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="co">    fig-responsive: true</span></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a><span class="co">    css: styles.css</span></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a><span class="co">  pdf:</span></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a><span class="co">    toc: false</span></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a><span class="co">    number-sections: true</span></span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a><span class="co">    geometry: "margin=1in"</span></span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a><span class="co">    fontsize: 10pt</span></span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a><span class="co">    keep-tex: false</span></span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a><span class="an">execute:</span></span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a><span class="co">  echo: false</span></span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a><span class="co">  warning: false</span></span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a><span class="co">  message: false</span></span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a><span class="co">  output: false</span></span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a><span class="co">  freeze: auto</span></span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a><span class="an">jupyter:</span><span class="co"> python3</span></span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-32"><a href="#cb1-32" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb1-33"><a href="#cb1-33" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: setup</span></span>
<span id="cb1-34"><a href="#cb1-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-35"><a href="#cb1-35" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> requests, io, warnings</span>
<span id="cb1-36"><a href="#cb1-36" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-37"><a href="#cb1-37" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-38"><a href="#cb1-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-39"><a href="#cb1-39" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb1-40"><a href="#cb1-40" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> plotnine <span class="im">import</span> <span class="op">*</span></span>
<span id="cb1-41"><a href="#cb1-41" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-42"><a href="#cb1-42" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> statsmodels.formula.api <span class="im">as</span> smf</span>
<span id="cb1-43"><a href="#cb1-43" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> pygam <span class="im">import</span> LinearGAM, s, f</span>
<span id="cb1-44"><a href="#cb1-44" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-45"><a href="#cb1-45" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.preprocessing <span class="im">import</span> StandardScaler</span>
<span id="cb1-46"><a href="#cb1-46" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.linear_model <span class="im">import</span> LinearRegression, LogisticRegression</span>
<span id="cb1-47"><a href="#cb1-47" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.ensemble <span class="im">import</span> RandomForestRegressor, RandomForestClassifier</span>
<span id="cb1-48"><a href="#cb1-48" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.metrics <span class="im">import</span> (</span>
<span id="cb1-49"><a href="#cb1-49" aria-hidden="true" tabindex="-1"></a>    mean_squared_error, mean_absolute_error, r2_score,</span>
<span id="cb1-50"><a href="#cb1-50" aria-hidden="true" tabindex="-1"></a>    accuracy_score, precision_score, recall_score, f1_score,</span>
<span id="cb1-51"><a href="#cb1-51" aria-hidden="true" tabindex="-1"></a>    roc_auc_score, roc_curve</span>
<span id="cb1-52"><a href="#cb1-52" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb1-53"><a href="#cb1-53" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> xgboost <span class="im">as</span> xgb</span>
<span id="cb1-54"><a href="#cb1-54" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-55"><a href="#cb1-55" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> IPython.display <span class="im">import</span> Markdown, display <span class="im">as</span> ipy_display</span>
<span id="cb1-56"><a href="#cb1-56" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-57"><a href="#cb1-57" aria-hidden="true" tabindex="-1"></a>warnings.filterwarnings(<span class="st">'ignore'</span>)</span>
<span id="cb1-58"><a href="#cb1-58" aria-hidden="true" tabindex="-1"></a>np.random.seed(<span class="dv">42</span>)</span>
<span id="cb1-59"><a href="#cb1-59" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-60"><a href="#cb1-60" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-61"><a href="#cb1-61" aria-hidden="true" tabindex="-1"></a><span class="fu"># Introduction</span></span>
<span id="cb1-62"><a href="#cb1-62" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-63"><a href="#cb1-63" aria-hidden="true" tabindex="-1"></a>The Toronto Transit Commission (TTC) carries over one million riders per day, making subway reliability a substantial piece of urban infrastructure. While many causes of delay — equipment failures, passenger incidents, security investigations — are random from a forecasting perspective, **weather** is one of the few systematic, externally observable, and forecastable variables that plausibly drives day-to-day delay patterns. Cold snaps freeze track switches; heavy snow buries third rails; extreme heat causes rail steel to expand. This project asks whether daily Toronto weather predicts TTC delays, by integrating 12 years of meteorological observations (2014–2025) with the City of Toronto's complete public record of subway delays.</span>
<span id="cb1-64"><a href="#cb1-64" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-65"><a href="#cb1-65" aria-hidden="true" tabindex="-1"></a><span class="fu">## Central Research Question</span></span>
<span id="cb1-66"><a href="#cb1-66" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-67"><a href="#cb1-67" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; **Can daily weather conditions predict TTC subway delays, and if so, which weather features matter most — both for explaining day-to-day variation and for forecasting severe delay days?**</span></span>
<span id="cb1-68"><a href="#cb1-68" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-69"><a href="#cb1-69" aria-hidden="true" tabindex="-1"></a>The question has two halves: an *explanatory* half (which weather variables associate with delay, and how?) and a *predictive* half (can that association be turned into a forecasting tool?). Each maps to a formal hypothesis with an explicit null.</span>
<span id="cb1-70"><a href="#cb1-70" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-71"><a href="#cb1-71" aria-hidden="true" tabindex="-1"></a>**H₁ — Explanatory.** Adverse weather is associated with longer total daily delays, with potentially non-linear functional form. *Null:* the partial slopes on precipitation and snowfall are zero, and the smooths are flat, after controlling for month and day-of-week. *Alternative:* slopes are positive; smooths exhibit non-linear structure (e.g., U-shaped temperature). H₁ is tested with OLS and a Generalized Additive Model (GAM).</span>
<span id="cb1-72"><a href="#cb1-72" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-73"><a href="#cb1-73" aria-hidden="true" tabindex="-1"></a>**H₂ — Predictive.** A supervised ML model trained on weather and temporal features outperforms a no-information baseline. *Null:* out-of-sample R² ≤ 0 and ROC-AUC ≤ 0.5. *Alternative:* R² &gt; 0 and ROC-AUC &gt; 0.5 on a chronologically held-out test set. H₂ is tested by training Linear/Logistic Regression, Random Forest, and XGBoost on 2014–2023 data and evaluating on 2024–2025.</span>
<span id="cb1-74"><a href="#cb1-74" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-75"><a href="#cb1-75" aria-hidden="true" tabindex="-1"></a>GitHub repo: <span class="ot">&lt;https://github.com/xiran-yin/JSC370-finalproject&gt;</span>.</span>
<span id="cb1-76"><a href="#cb1-76" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-77"><a href="#cb1-77" aria-hidden="true" tabindex="-1"></a><span class="fu"># Methods</span></span>
<span id="cb1-78"><a href="#cb1-78" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-79"><a href="#cb1-79" aria-hidden="true" tabindex="-1"></a><span class="fu">## Data Sources</span></span>
<span id="cb1-80"><a href="#cb1-80" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-81"><a href="#cb1-81" aria-hidden="true" tabindex="-1"></a>Two independent sources are combined: (1) **Weather** — [Open-Meteo Historical Weather API](https://open-meteo.com/en/docs/historical-weather-api), Toronto (43.7064°N, −79.3986°W), daily aggregates 2014–2026; (2) **TTC delays** — City of Toronto Open Data Portal <span class="co">[</span><span class="ot">`ttc-subway-delay-data`</span><span class="co">](https://open.toronto.ca/dataset/ttc-subway-delay-data/)</span>, every recorded incident 2014–2025, retrieved via the CKAN API.</span>
<span id="cb1-82"><a href="#cb1-82" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-83"><a href="#cb1-83" aria-hidden="true" tabindex="-1"></a><span class="fu">## Data Acquisition and Cleaning</span></span>
<span id="cb1-84"><a href="#cb1-84" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-87"><a href="#cb1-87" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb1-88"><a href="#cb1-88" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: weather</span></span>
<span id="cb1-89"><a href="#cb1-89" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-90"><a href="#cb1-90" aria-hidden="true" tabindex="-1"></a>start_date, end_date <span class="op">=</span> <span class="st">"2014-01-01"</span>, <span class="st">"2026-01-01"</span></span>
<span id="cb1-91"><a href="#cb1-91" aria-hidden="true" tabindex="-1"></a>url <span class="op">=</span> (</span>
<span id="cb1-92"><a href="#cb1-92" aria-hidden="true" tabindex="-1"></a>    <span class="ss">f"https://archive-api.open-meteo.com/v1/archive?"</span></span>
<span id="cb1-93"><a href="#cb1-93" aria-hidden="true" tabindex="-1"></a>    <span class="ss">f"latitude=43.7064&amp;longitude=-79.3986&amp;start_date=</span><span class="sc">{</span>start_date<span class="sc">}</span><span class="ss">&amp;end_date=</span><span class="sc">{</span>end_date<span class="sc">}</span><span class="ss">"</span></span>
<span id="cb1-94"><a href="#cb1-94" aria-hidden="true" tabindex="-1"></a>    <span class="ss">f"&amp;daily=temperature_2m_max,temperature_2m_min,apparent_temperature_max,"</span></span>
<span id="cb1-95"><a href="#cb1-95" aria-hidden="true" tabindex="-1"></a>    <span class="ss">f"precipitation_sum,snowfall_sum,wind_speed_10m_max,wind_gusts_10m_max,"</span></span>
<span id="cb1-96"><a href="#cb1-96" aria-hidden="true" tabindex="-1"></a>    <span class="ss">f"precipitation_hours&amp;timezone=America%2FNew_York"</span></span>
<span id="cb1-97"><a href="#cb1-97" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb1-98"><a href="#cb1-98" aria-hidden="true" tabindex="-1"></a>w <span class="op">=</span> requests.get(url).json()[<span class="st">'daily'</span>]</span>
<span id="cb1-99"><a href="#cb1-99" aria-hidden="true" tabindex="-1"></a>df_weather <span class="op">=</span> pd.DataFrame({</span>
<span id="cb1-100"><a href="#cb1-100" aria-hidden="true" tabindex="-1"></a>    <span class="st">'date'</span>: pd.to_datetime(w[<span class="st">'time'</span>]),</span>
<span id="cb1-101"><a href="#cb1-101" aria-hidden="true" tabindex="-1"></a>    <span class="st">'temp_max'</span>: w[<span class="st">'temperature_2m_max'</span>], <span class="st">'temp_min'</span>: w[<span class="st">'temperature_2m_min'</span>],</span>
<span id="cb1-102"><a href="#cb1-102" aria-hidden="true" tabindex="-1"></a>    <span class="st">'precip_mm'</span>: w[<span class="st">'precipitation_sum'</span>], <span class="st">'precip_hours'</span>: w[<span class="st">'precipitation_hours'</span>],</span>
<span id="cb1-103"><a href="#cb1-103" aria-hidden="true" tabindex="-1"></a>    <span class="st">'snowfall_cm'</span>: w[<span class="st">'snowfall_sum'</span>],</span>
<span id="cb1-104"><a href="#cb1-104" aria-hidden="true" tabindex="-1"></a>    <span class="st">'gust_speed'</span>: w[<span class="st">'wind_gusts_10m_max'</span>]</span>
<span id="cb1-105"><a href="#cb1-105" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb1-106"><a href="#cb1-106" aria-hidden="true" tabindex="-1"></a>df_weather[<span class="st">'precip_intensity'</span>] <span class="op">=</span> df_weather.<span class="bu">apply</span>(</span>
<span id="cb1-107"><a href="#cb1-107" aria-hidden="true" tabindex="-1"></a>    <span class="kw">lambda</span> x: x[<span class="st">'precip_mm'</span>]<span class="op">/</span>x[<span class="st">'precip_hours'</span>] <span class="cf">if</span> x[<span class="st">'precip_hours'</span>]<span class="op">&gt;</span><span class="dv">0</span> <span class="cf">else</span> <span class="dv">0</span>, axis<span class="op">=</span><span class="dv">1</span></span>
<span id="cb1-108"><a href="#cb1-108" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb1-109"><a href="#cb1-109" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-110"><a href="#cb1-110" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-113"><a href="#cb1-113" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb1-114"><a href="#cb1-114" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: ttc</span></span>
<span id="cb1-115"><a href="#cb1-115" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-116"><a href="#cb1-116" aria-hidden="true" tabindex="-1"></a>base_url <span class="op">=</span> <span class="st">"https://ckan0.cf.opendata.inter.prod-toronto.ca/api/3/action/package_show"</span></span>
<span id="cb1-117"><a href="#cb1-117" aria-hidden="true" tabindex="-1"></a>headers <span class="op">=</span> {<span class="st">'User-Agent'</span>: <span class="st">'Mozilla/5.0'</span>}</span>
<span id="cb1-118"><a href="#cb1-118" aria-hidden="true" tabindex="-1"></a>response <span class="op">=</span> requests.get(base_url, params<span class="op">=</span>{<span class="st">"id"</span>: <span class="st">"ttc-subway-delay-data"</span>}, headers<span class="op">=</span>headers)</span>
<span id="cb1-119"><a href="#cb1-119" aria-hidden="true" tabindex="-1"></a>all_data <span class="op">=</span> []</span>
<span id="cb1-120"><a href="#cb1-120" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-121"><a href="#cb1-121" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> response.status_code <span class="op">==</span> <span class="dv">200</span>:</span>
<span id="cb1-122"><a href="#cb1-122" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> res <span class="kw">in</span> response.json()[<span class="st">"result"</span>][<span class="st">"resources"</span>]:</span>
<span id="cb1-123"><a href="#cb1-123" aria-hidden="true" tabindex="-1"></a>        fmt <span class="op">=</span> res[<span class="st">"format"</span>].upper()</span>
<span id="cb1-124"><a href="#cb1-124" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> fmt <span class="kw">in</span> [<span class="st">"CSV"</span>,<span class="st">"XLSX"</span>,<span class="st">"XLS"</span>]:</span>
<span id="cb1-125"><a href="#cb1-125" aria-hidden="true" tabindex="-1"></a>            <span class="cf">try</span>:</span>
<span id="cb1-126"><a href="#cb1-126" aria-hidden="true" tabindex="-1"></a>                file_res <span class="op">=</span> requests.get(res[<span class="st">"url"</span>], headers<span class="op">=</span>headers, timeout<span class="op">=</span><span class="dv">30</span>)</span>
<span id="cb1-127"><a href="#cb1-127" aria-hidden="true" tabindex="-1"></a>                <span class="cf">if</span> fmt <span class="op">==</span> <span class="st">"CSV"</span>:</span>
<span id="cb1-128"><a href="#cb1-128" aria-hidden="true" tabindex="-1"></a>                    df_temp <span class="op">=</span> pd.read_csv(</span>
<span id="cb1-129"><a href="#cb1-129" aria-hidden="true" tabindex="-1"></a>                        io.StringIO(file_res.content.decode(<span class="st">'utf-8'</span>, errors<span class="op">=</span><span class="st">'ignore'</span>)),</span>
<span id="cb1-130"><a href="#cb1-130" aria-hidden="true" tabindex="-1"></a>                        low_memory<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb1-131"><a href="#cb1-131" aria-hidden="true" tabindex="-1"></a>                <span class="cf">else</span>:</span>
<span id="cb1-132"><a href="#cb1-132" aria-hidden="true" tabindex="-1"></a>                    excel_dict <span class="op">=</span> pd.read_excel(io.BytesIO(file_res.content), sheet_name<span class="op">=</span><span class="va">None</span>)</span>
<span id="cb1-133"><a href="#cb1-133" aria-hidden="true" tabindex="-1"></a>                    df_temp <span class="op">=</span> pd.concat(excel_dict.values(), ignore_index<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb1-134"><a href="#cb1-134" aria-hidden="true" tabindex="-1"></a>                date_cands <span class="op">=</span> [<span class="st">'date'</span>,<span class="st">'occ_date'</span>,<span class="st">'occurrence date'</span>,<span class="st">'report date'</span>]</span>
<span id="cb1-135"><a href="#cb1-135" aria-hidden="true" tabindex="-1"></a>                delay_cands <span class="op">=</span> [<span class="st">'delay'</span>,<span class="st">'min_delay'</span>,<span class="st">'min delay'</span>,<span class="st">'minimum delay'</span>]</span>
<span id="cb1-136"><a href="#cb1-136" aria-hidden="true" tabindex="-1"></a>                fd <span class="op">=</span> <span class="bu">next</span>((c <span class="cf">for</span> c <span class="kw">in</span> df_temp.columns <span class="cf">if</span> <span class="bu">any</span>(x <span class="kw">in</span> c.lower() <span class="cf">for</span> x <span class="kw">in</span> date_cands)), <span class="va">None</span>)</span>
<span id="cb1-137"><a href="#cb1-137" aria-hidden="true" tabindex="-1"></a>                fdel <span class="op">=</span> <span class="bu">next</span>((c <span class="cf">for</span> c <span class="kw">in</span> df_temp.columns <span class="cf">if</span> <span class="bu">any</span>(x <span class="kw">in</span> c.lower() <span class="cf">for</span> x <span class="kw">in</span> delay_cands)), <span class="va">None</span>)</span>
<span id="cb1-138"><a href="#cb1-138" aria-hidden="true" tabindex="-1"></a>                <span class="cf">if</span> fd <span class="kw">and</span> fdel:</span>
<span id="cb1-139"><a href="#cb1-139" aria-hidden="true" tabindex="-1"></a>                    df_temp <span class="op">=</span> df_temp.rename(columns<span class="op">=</span>{fd: <span class="st">'date'</span>, fdel: <span class="st">'min_delay'</span>})</span>
<span id="cb1-140"><a href="#cb1-140" aria-hidden="true" tabindex="-1"></a>                    df_temp[<span class="st">'date'</span>] <span class="op">=</span> pd.to_datetime(df_temp[<span class="st">'date'</span>], errors<span class="op">=</span><span class="st">'coerce'</span>)</span>
<span id="cb1-141"><a href="#cb1-141" aria-hidden="true" tabindex="-1"></a>                    all_data.append(df_temp[[<span class="st">'date'</span>,<span class="st">'min_delay'</span>]].dropna(subset<span class="op">=</span>[<span class="st">'date'</span>]))</span>
<span id="cb1-142"><a href="#cb1-142" aria-hidden="true" tabindex="-1"></a>            <span class="cf">except</span> <span class="pp">Exception</span>:</span>
<span id="cb1-143"><a href="#cb1-143" aria-hidden="true" tabindex="-1"></a>                <span class="cf">pass</span></span>
<span id="cb1-144"><a href="#cb1-144" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-145"><a href="#cb1-145" aria-hidden="true" tabindex="-1"></a>df_ttc_raw <span class="op">=</span> pd.concat(all_data, ignore_index<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb1-146"><a href="#cb1-146" aria-hidden="true" tabindex="-1"></a>df_ttc_daily <span class="op">=</span> df_ttc_raw.groupby(<span class="st">'date'</span>).agg(</span>
<span id="cb1-147"><a href="#cb1-147" aria-hidden="true" tabindex="-1"></a>    total_delay_mins<span class="op">=</span>(<span class="st">'min_delay'</span>,<span class="st">'sum'</span>),</span>
<span id="cb1-148"><a href="#cb1-148" aria-hidden="true" tabindex="-1"></a>    total_incidents <span class="op">=</span>(<span class="st">'min_delay'</span>,<span class="st">'count'</span>)).reset_index()</span>
<span id="cb1-149"><a href="#cb1-149" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-150"><a href="#cb1-150" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-151"><a href="#cb1-151" aria-hidden="true" tabindex="-1"></a>Weather acquisition is one HTTPS GET to the Open-Meteo archive. TTC acquisition handles three obstacles: (i) **format dispatching** (mixed CSV/XLSX requires different pandas readers); (ii) **multi-sheet Excel** (2014–2017 files split records across 12 monthly worksheets — `sheet_name=None` is required to avoid silently dropping ~92% of those years); (iii) **inconsistent column names** ("Date" / "Occurrence Date"; "Min Delay" / "min_delay") — handled by substring-matching against known synonyms.</span>
<span id="cb1-152"><a href="#cb1-152" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-155"><a href="#cb1-155" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb1-156"><a href="#cb1-156" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: merge</span></span>
<span id="cb1-157"><a href="#cb1-157" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-158"><a href="#cb1-158" aria-hidden="true" tabindex="-1"></a>df_merged <span class="op">=</span> pd.merge(df_ttc_daily, df_weather, on<span class="op">=</span><span class="st">'date'</span>, how<span class="op">=</span><span class="st">'inner'</span>)</span>
<span id="cb1-159"><a href="#cb1-159" aria-hidden="true" tabindex="-1"></a>df_merged[<span class="st">'month_num'</span>]     <span class="op">=</span> df_merged[<span class="st">'date'</span>].dt.month</span>
<span id="cb1-160"><a href="#cb1-160" aria-hidden="true" tabindex="-1"></a>df_merged[<span class="st">'month'</span>]         <span class="op">=</span> df_merged[<span class="st">'date'</span>].dt.month_name()</span>
<span id="cb1-161"><a href="#cb1-161" aria-hidden="true" tabindex="-1"></a>df_merged[<span class="st">'dow_num'</span>]       <span class="op">=</span> df_merged[<span class="st">'date'</span>].dt.dayofweek</span>
<span id="cb1-162"><a href="#cb1-162" aria-hidden="true" tabindex="-1"></a>df_merged[<span class="st">'is_weekend'</span>]    <span class="op">=</span> (df_merged[<span class="st">'dow_num'</span>] <span class="op">&gt;=</span> <span class="dv">5</span>).astype(<span class="bu">int</span>)</span>
<span id="cb1-163"><a href="#cb1-163" aria-hidden="true" tabindex="-1"></a>df_merged[<span class="st">'mean_temp_c'</span>]   <span class="op">=</span> (df_merged[<span class="st">'temp_max'</span>]<span class="op">+</span>df_merged[<span class="st">'temp_min'</span>])<span class="op">/</span><span class="dv">2</span></span>
<span id="cb1-164"><a href="#cb1-164" aria-hidden="true" tabindex="-1"></a>df_merged[<span class="st">'temp_range'</span>]    <span class="op">=</span> df_merged[<span class="st">'temp_max'</span>]<span class="op">-</span>df_merged[<span class="st">'temp_min'</span>]</span>
<span id="cb1-165"><a href="#cb1-165" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-166"><a href="#cb1-166" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> classify_weather(row):</span>
<span id="cb1-167"><a href="#cb1-167" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> row[<span class="st">'precip_mm'</span>]<span class="op">&gt;=</span><span class="dv">10</span> <span class="kw">or</span> row[<span class="st">'snowfall_cm'</span>]<span class="op">&gt;=</span><span class="dv">5</span>: <span class="cf">return</span> <span class="st">'Heavy Rain/Snow'</span></span>
<span id="cb1-168"><a href="#cb1-168" aria-hidden="true" tabindex="-1"></a>    <span class="cf">elif</span> row[<span class="st">'precip_mm'</span>]<span class="op">&gt;</span><span class="dv">0</span> <span class="kw">or</span> row[<span class="st">'snowfall_cm'</span>]<span class="op">&gt;</span><span class="dv">0</span>: <span class="cf">return</span> <span class="st">'Light Rain/Snow'</span></span>
<span id="cb1-169"><a href="#cb1-169" aria-hidden="true" tabindex="-1"></a>    <span class="cf">else</span>: <span class="cf">return</span> <span class="st">'Clear'</span></span>
<span id="cb1-170"><a href="#cb1-170" aria-hidden="true" tabindex="-1"></a>df_merged[<span class="st">'weather_type'</span>] <span class="op">=</span> df_merged.<span class="bu">apply</span>(classify_weather, axis<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb1-171"><a href="#cb1-171" aria-hidden="true" tabindex="-1"></a>df_merged[<span class="st">'weather_type'</span>] <span class="op">=</span> pd.Categorical(</span>
<span id="cb1-172"><a href="#cb1-172" aria-hidden="true" tabindex="-1"></a>    df_merged[<span class="st">'weather_type'</span>],</span>
<span id="cb1-173"><a href="#cb1-173" aria-hidden="true" tabindex="-1"></a>    categories<span class="op">=</span>[<span class="st">'Clear'</span>,<span class="st">'Light Rain/Snow'</span>,<span class="st">'Heavy Rain/Snow'</span>], ordered<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb1-174"><a href="#cb1-174" aria-hidden="true" tabindex="-1"></a>df_merged[<span class="st">'month_cat'</span>] <span class="op">=</span> pd.Categorical(df_merged[<span class="st">'month'</span>])</span>
<span id="cb1-175"><a href="#cb1-175" aria-hidden="true" tabindex="-1"></a>df_merged <span class="op">=</span> df_merged.sort_values(<span class="st">'date'</span>).reset_index(drop<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb1-176"><a href="#cb1-176" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-177"><a href="#cb1-177" aria-hidden="true" tabindex="-1"></a><span class="co"># Detrending: subtract calendar-month mean to remove the post-2021 baseline rise.</span></span>
<span id="cb1-178"><a href="#cb1-178" aria-hidden="true" tabindex="-1"></a><span class="co"># Models predict the *anomaly* (deviation from the month's mean) rather than the</span></span>
<span id="cb1-179"><a href="#cb1-179" aria-hidden="true" tabindex="-1"></a><span class="co"># absolute level, isolating the weather signal from non-stationary trend.</span></span>
<span id="cb1-180"><a href="#cb1-180" aria-hidden="true" tabindex="-1"></a>df_merged[<span class="st">'month_year'</span>] <span class="op">=</span> df_merged[<span class="st">'date'</span>].dt.to_period(<span class="st">'M'</span>)</span>
<span id="cb1-181"><a href="#cb1-181" aria-hidden="true" tabindex="-1"></a>month_means <span class="op">=</span> df_merged.groupby(<span class="st">'month_year'</span>)[<span class="st">'total_delay_mins'</span>].transform(<span class="st">'mean'</span>)</span>
<span id="cb1-182"><a href="#cb1-182" aria-hidden="true" tabindex="-1"></a>df_merged[<span class="st">'delay_anomaly'</span>] <span class="op">=</span> df_merged[<span class="st">'total_delay_mins'</span>] <span class="op">-</span> month_means</span>
<span id="cb1-183"><a href="#cb1-183" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-184"><a href="#cb1-184" aria-hidden="true" tabindex="-1"></a><span class="co"># Severe-day target uses the training-period 75th percentile of the anomaly</span></span>
<span id="cb1-185"><a href="#cb1-185" aria-hidden="true" tabindex="-1"></a>train_mask <span class="op">=</span> df_merged[<span class="st">'date'</span>] <span class="op">&lt;</span> pd.Timestamp(<span class="st">'2024-01-01'</span>)</span>
<span id="cb1-186"><a href="#cb1-186" aria-hidden="true" tabindex="-1"></a>anomaly_q3 <span class="op">=</span> df_merged.loc[train_mask, <span class="st">'delay_anomaly'</span>].quantile(<span class="fl">0.75</span>)</span>
<span id="cb1-187"><a href="#cb1-187" aria-hidden="true" tabindex="-1"></a>df_merged[<span class="st">'is_severe'</span>] <span class="op">=</span> (df_merged[<span class="st">'delay_anomaly'</span>] <span class="op">&gt;=</span> anomaly_q3).astype(<span class="bu">int</span>)</span>
<span id="cb1-188"><a href="#cb1-188" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-189"><a href="#cb1-189" aria-hidden="true" tabindex="-1"></a>n_obs <span class="op">=</span> df_merged.shape[<span class="dv">0</span>]</span>
<span id="cb1-190"><a href="#cb1-190" aria-hidden="true" tabindex="-1"></a>mean_delay_2014 <span class="op">=</span> df_merged[df_merged[<span class="st">'date'</span>].dt.year<span class="op">==</span><span class="dv">2014</span>][<span class="st">'total_delay_mins'</span>].mean()</span>
<span id="cb1-191"><a href="#cb1-191" aria-hidden="true" tabindex="-1"></a>mean_delay_2022 <span class="op">=</span> df_merged[df_merged[<span class="st">'date'</span>].dt.year<span class="op">==</span><span class="dv">2022</span>][<span class="st">'total_delay_mins'</span>].mean()</span>
<span id="cb1-192"><a href="#cb1-192" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-193"><a href="#cb1-193" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-194"><a href="#cb1-194" aria-hidden="true" tabindex="-1"></a>The merged dataset has **`{python} f"{n_obs:,}"` daily observations**. A three-level **categorical weather severity variable** is derived using two fixed breakpoints — `precip_mm ≥ 10` *or* `snowfall_cm ≥ 5` for "Heavy", either positive but neither at threshold for "Light", otherwise "Clear" — corresponding to Environment Canada's heavy-rain advisory level. Because the TTC has experienced a structural rise in delays since 2021 (mean total daily delay rose from ~`{python} f"{mean_delay_2014:.0f}"` min/day in 2014 to ~`{python} f"{mean_delay_2022:.0f}"` min/day by 2022), we **detrend** the predictive target by subtracting each day's calendar-month mean. The detrended target `delay_anomaly` represents how much worse (or better) a given day was than typical for that month, isolating weather-driven variation from baseline drift. The binary classification target `is_severe` flags days at or above the **training-period** 75th percentile of <span class="in">`delay_anomaly`</span>, so that "severe" means the same thing across the 12-year window.</span>
<span id="cb1-195"><a href="#cb1-195" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-196"><a href="#cb1-196" aria-hidden="true" tabindex="-1"></a><span class="fu">## Statistical and Machine-Learning Methods</span></span>
<span id="cb1-197"><a href="#cb1-197" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-198"><a href="#cb1-198" aria-hidden="true" tabindex="-1"></a>**Inferential** (testing H₁): (i) **OLS multiple regression** of `total_delay_mins` on precipitation, snowfall, gust speed, mean temperature, weekend, and month fixed effects, as a linear baseline. (ii) **GAM** via <span class="in">`pygam.LinearGAM(s(precip) + s(temp) + f(weekend) + f(month))`</span>, with 20-knot penalized cubic splines and smoothing parameters chosen by generalized cross-validation, to capture non-linearity.</span>
<span id="cb1-199"><a href="#cb1-199" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-200"><a href="#cb1-200" aria-hidden="true" tabindex="-1"></a>**Predictive** (testing H₂): three supervised models fit twice — once for regression (target: `delay_anomaly`) and once for classification (target: `is_severe`). The models are **Linear/Logistic Regression** (baseline), **Random Forest** (`sklearn.ensemble`), and **XGBoost** (`xgboost`). Hyperparameters: RF — `n_estimators=300–400`, `max_depth=8–10`; XGBoost — `n_estimators=400`, `max_depth=6`, `learning_rate=0.05`, `subsample=0.8`. Twelve features are used: `precip_mm`, `snowfall_cm`, `precip_hours`, `precip_intensity`, `temp_max`, `temp_min`, `mean_temp_c`, `temp_range`, `gust_speed`, `is_weekend`, `month_num`, `dow_num`. The data are split **chronologically** — train on 2014-01-01 to 2023-12-31, test on 2024-01-01 onward — to prevent the model from learning future information. Regression metrics: RMSE, MAE, R². Classification metrics: accuracy, precision, recall, F1, ROC-AUC.</span>
<span id="cb1-201"><a href="#cb1-201" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-202"><a href="#cb1-202" aria-hidden="true" tabindex="-1"></a><span class="fu"># Results</span></span>
<span id="cb1-203"><a href="#cb1-203" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-204"><a href="#cb1-204" aria-hidden="true" tabindex="-1"></a><span class="fu">## Descriptive Statistics</span></span>
<span id="cb1-205"><a href="#cb1-205" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-208"><a href="#cb1-208" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb1-209"><a href="#cb1-209" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: tbl-summary</span></span>
<span id="cb1-210"><a href="#cb1-210" aria-hidden="true" tabindex="-1"></a><span class="co">#| output: true</span></span>
<span id="cb1-211"><a href="#cb1-211" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-212"><a href="#cb1-212" aria-hidden="true" tabindex="-1"></a>desc <span class="op">=</span> (df_merged[[<span class="st">'total_delay_mins'</span>,<span class="st">'total_incidents'</span>,<span class="st">'mean_temp_c'</span>,</span>
<span id="cb1-213"><a href="#cb1-213" aria-hidden="true" tabindex="-1"></a>                    <span class="st">'precip_mm'</span>,<span class="st">'snowfall_cm'</span>,<span class="st">'gust_speed'</span>]]</span>
<span id="cb1-214"><a href="#cb1-214" aria-hidden="true" tabindex="-1"></a>        .describe().<span class="bu">round</span>(<span class="dv">1</span>).T)</span>
<span id="cb1-215"><a href="#cb1-215" aria-hidden="true" tabindex="-1"></a>desc.index <span class="op">=</span> [<span class="st">'Total Delay (min)'</span>,<span class="st">'Total Incidents'</span>,<span class="st">'Mean Temp (°C)'</span>,</span>
<span id="cb1-216"><a href="#cb1-216" aria-hidden="true" tabindex="-1"></a>              <span class="st">'Precip (mm)'</span>,<span class="st">'Snowfall (cm)'</span>,<span class="st">'Gust Speed (km/h)'</span>]</span>
<span id="cb1-217"><a href="#cb1-217" aria-hidden="true" tabindex="-1"></a>desc <span class="op">=</span> desc[[<span class="st">'count'</span>,<span class="st">'mean'</span>,<span class="st">'std'</span>,<span class="st">'min'</span>,<span class="st">'50%'</span>,<span class="st">'max'</span>]]</span>
<span id="cb1-218"><a href="#cb1-218" aria-hidden="true" tabindex="-1"></a>desc.columns <span class="op">=</span> [<span class="st">'N'</span>,<span class="st">'Mean'</span>,<span class="st">'SD'</span>,<span class="st">'Min'</span>,<span class="st">'Median'</span>,<span class="st">'Max'</span>]</span>
<span id="cb1-219"><a href="#cb1-219" aria-hidden="true" tabindex="-1"></a>desc[<span class="st">'N'</span>] <span class="op">=</span> desc[<span class="st">'N'</span>].astype(<span class="bu">int</span>)</span>
<span id="cb1-220"><a href="#cb1-220" aria-hidden="true" tabindex="-1"></a>ipy_display(Markdown(<span class="st">"**Table 1.** Descriptive statistics, 2014–2025.</span><span class="ch">\n\n</span><span class="st">"</span> <span class="op">+</span> desc.to_markdown()))</span>
<span id="cb1-221"><a href="#cb1-221" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-222"><a href="#cb1-222" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-225"><a href="#cb1-225" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb1-226"><a href="#cb1-226" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: tbl-weather</span></span>
<span id="cb1-227"><a href="#cb1-227" aria-hidden="true" tabindex="-1"></a><span class="co">#| output: true</span></span>
<span id="cb1-228"><a href="#cb1-228" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-229"><a href="#cb1-229" aria-hidden="true" tabindex="-1"></a>st <span class="op">=</span> df_merged.groupby(<span class="st">'weather_type'</span>, observed<span class="op">=</span><span class="va">True</span>).agg(</span>
<span id="cb1-230"><a href="#cb1-230" aria-hidden="true" tabindex="-1"></a>    N<span class="op">=</span>(<span class="st">'date'</span>,<span class="st">'count'</span>), Mean<span class="op">=</span>(<span class="st">'total_delay_mins'</span>,<span class="st">'mean'</span>),</span>
<span id="cb1-231"><a href="#cb1-231" aria-hidden="true" tabindex="-1"></a>    SD<span class="op">=</span>(<span class="st">'total_delay_mins'</span>,<span class="st">'std'</span>), Median<span class="op">=</span>(<span class="st">'total_delay_mins'</span>,<span class="st">'median'</span>),</span>
<span id="cb1-232"><a href="#cb1-232" aria-hidden="true" tabindex="-1"></a>).<span class="bu">round</span>(<span class="dv">1</span>).reset_index()</span>
<span id="cb1-233"><a href="#cb1-233" aria-hidden="true" tabindex="-1"></a>st.columns <span class="op">=</span> [<span class="st">'Weather Type'</span>,<span class="st">'N (days)'</span>,<span class="st">'Mean Delay (min)'</span>,<span class="st">'SD'</span>,<span class="st">'Median (min)'</span>]</span>
<span id="cb1-234"><a href="#cb1-234" aria-hidden="true" tabindex="-1"></a>ipy_display(Markdown(<span class="st">"**Table 2.** Mean delay by weather category.</span><span class="ch">\n\n</span><span class="st">"</span> <span class="op">+</span> st.to_markdown(index<span class="op">=</span><span class="va">False</span>)))</span>
<span id="cb1-235"><a href="#cb1-235" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-236"><a href="#cb1-236" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-237"><a href="#cb1-237" aria-hidden="true" tabindex="-1"></a>System-wide total delay averages 144 min/day with a heavy right tail. Mean total delay rises monotonically from Clear (~137 min) to Light (~146 min) to Heavy (~179 min), consistent with severe events triggering disproportionate disruption.</span>
<span id="cb1-238"><a href="#cb1-238" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-239"><a href="#cb1-239" aria-hidden="true" tabindex="-1"></a><span class="fu">## H₁ — Explanatory Models</span></span>
<span id="cb1-240"><a href="#cb1-240" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-243"><a href="#cb1-243" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb1-244"><a href="#cb1-244" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: ols</span></span>
<span id="cb1-245"><a href="#cb1-245" aria-hidden="true" tabindex="-1"></a><span class="co">#| output: true</span></span>
<span id="cb1-246"><a href="#cb1-246" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-247"><a href="#cb1-247" aria-hidden="true" tabindex="-1"></a>m_ols <span class="op">=</span> smf.ols(</span>
<span id="cb1-248"><a href="#cb1-248" aria-hidden="true" tabindex="-1"></a>    <span class="st">"total_delay_mins ~ precip_mm + snowfall_cm + gust_speed + mean_temp_c "</span></span>
<span id="cb1-249"><a href="#cb1-249" aria-hidden="true" tabindex="-1"></a>    <span class="st">"+ is_weekend + C(month_cat)"</span>, data<span class="op">=</span>df_merged).fit()</span>
<span id="cb1-250"><a href="#cb1-250" aria-hidden="true" tabindex="-1"></a>ols_r2 <span class="op">=</span> m_ols.rsquared</span>
<span id="cb1-251"><a href="#cb1-251" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-252"><a href="#cb1-252" aria-hidden="true" tabindex="-1"></a>vars_  <span class="op">=</span> [<span class="st">'precip_mm'</span>,<span class="st">'snowfall_cm'</span>,<span class="st">'gust_speed'</span>,<span class="st">'mean_temp_c'</span>,<span class="st">'is_weekend'</span>]</span>
<span id="cb1-253"><a href="#cb1-253" aria-hidden="true" tabindex="-1"></a>labels <span class="op">=</span> [<span class="st">'Precipitation (mm)'</span>,<span class="st">'Snowfall (cm)'</span>,<span class="st">'Gust Speed (km/h)'</span>,</span>
<span id="cb1-254"><a href="#cb1-254" aria-hidden="true" tabindex="-1"></a>          <span class="st">'Mean Temp (°C)'</span>,<span class="st">'Weekend (indicator)'</span>]</span>
<span id="cb1-255"><a href="#cb1-255" aria-hidden="true" tabindex="-1"></a>rows <span class="op">=</span> []</span>
<span id="cb1-256"><a href="#cb1-256" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> v, l <span class="kw">in</span> <span class="bu">zip</span>(vars_, labels):</span>
<span id="cb1-257"><a href="#cb1-257" aria-hidden="true" tabindex="-1"></a>    rows.append({</span>
<span id="cb1-258"><a href="#cb1-258" aria-hidden="true" tabindex="-1"></a>        <span class="st">'Predictor'</span>: l,</span>
<span id="cb1-259"><a href="#cb1-259" aria-hidden="true" tabindex="-1"></a>        <span class="st">'Coef'</span>:  <span class="ss">f"</span><span class="sc">{</span>m_ols<span class="sc">.</span>params[v]<span class="sc">:.3f}</span><span class="ss">"</span>,</span>
<span id="cb1-260"><a href="#cb1-260" aria-hidden="true" tabindex="-1"></a>        <span class="st">'SE'</span>:    <span class="ss">f"</span><span class="sc">{</span>m_ols<span class="sc">.</span>bse[v]<span class="sc">:.3f}</span><span class="ss">"</span>,</span>
<span id="cb1-261"><a href="#cb1-261" aria-hidden="true" tabindex="-1"></a>        <span class="st">'t'</span>:     <span class="ss">f"</span><span class="sc">{</span>m_ols<span class="sc">.</span>tvalues[v]<span class="sc">:.2f}</span><span class="ss">"</span>,</span>
<span id="cb1-262"><a href="#cb1-262" aria-hidden="true" tabindex="-1"></a>        <span class="st">'p'</span>:     (<span class="ss">f"</span><span class="sc">{</span>m_ols<span class="sc">.</span>pvalues[v]<span class="sc">:.4f}</span><span class="ss">"</span> <span class="cf">if</span> m_ols.pvalues[v]<span class="op">&gt;=</span><span class="fl">1e-4</span> <span class="cf">else</span> <span class="st">"&lt;0.001"</span>),</span>
<span id="cb1-263"><a href="#cb1-263" aria-hidden="true" tabindex="-1"></a>    })</span>
<span id="cb1-264"><a href="#cb1-264" aria-hidden="true" tabindex="-1"></a>df_ols_table <span class="op">=</span> pd.DataFrame(rows)</span>
<span id="cb1-265"><a href="#cb1-265" aria-hidden="true" tabindex="-1"></a>ipy_display(Markdown(</span>
<span id="cb1-266"><a href="#cb1-266" aria-hidden="true" tabindex="-1"></a>    <span class="ss">f"**Table 3.** OLS regression of total daily delay. R² = </span><span class="sc">{</span>ols_r2<span class="sc">:.3f}</span><span class="ss">. Month FE included.</span><span class="ch">\n\n</span><span class="ss">"</span> <span class="op">+</span></span>
<span id="cb1-267"><a href="#cb1-267" aria-hidden="true" tabindex="-1"></a>    df_ols_table.to_markdown(index<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb1-268"><a href="#cb1-268" aria-hidden="true" tabindex="-1"></a>))</span>
<span id="cb1-269"><a href="#cb1-269" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-270"><a href="#cb1-270" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-271"><a href="#cb1-271" aria-hidden="true" tabindex="-1"></a>OLS shows three results. (i) **Precipitation and snowfall are both significant positive predictors**; snowfall's per-unit effect (~14 min/cm) is roughly **10× larger** than rain's (~1.2 min/mm) — frozen precipitation is operationally far more disruptive. (ii) **Weekends lose ~32 fewer minutes** to delay than weather-matched weekdays. (iii) **Mean temperature is non-significant** linearly — an artifact, since the GAM below shows a U-shape that a single linear coefficient cannot capture.</span>
<span id="cb1-272"><a href="#cb1-272" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-275"><a href="#cb1-275" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb1-276"><a href="#cb1-276" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: gam</span></span>
<span id="cb1-277"><a href="#cb1-277" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-278"><a href="#cb1-278" aria-hidden="true" tabindex="-1"></a>X_gam <span class="op">=</span> df_merged[[<span class="st">'precip_mm'</span>,<span class="st">'mean_temp_c'</span>,<span class="st">'is_weekend'</span>,<span class="st">'month_num'</span>]].values</span>
<span id="cb1-279"><a href="#cb1-279" aria-hidden="true" tabindex="-1"></a>y_gam <span class="op">=</span> df_merged[<span class="st">'total_delay_mins'</span>].values</span>
<span id="cb1-280"><a href="#cb1-280" aria-hidden="true" tabindex="-1"></a>gam <span class="op">=</span> LinearGAM(s(<span class="dv">0</span>) <span class="op">+</span> s(<span class="dv">1</span>) <span class="op">+</span> f(<span class="dv">2</span>) <span class="op">+</span> f(<span class="dv">3</span>)).fit(X_gam, y_gam)</span>
<span id="cb1-281"><a href="#cb1-281" aria-hidden="true" tabindex="-1"></a>gam_r2 <span class="op">=</span> gam.statistics_[<span class="st">'pseudo_r2'</span>][<span class="st">'explained_deviance'</span>]</span>
<span id="cb1-282"><a href="#cb1-282" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-283"><a href="#cb1-283" aria-hidden="true" tabindex="-1"></a>x_range <span class="op">=</span> np.linspace(X_gam[:,<span class="dv">1</span>].<span class="bu">min</span>(), X_gam[:,<span class="dv">1</span>].<span class="bu">max</span>(), <span class="dv">200</span>)</span>
<span id="cb1-284"><a href="#cb1-284" aria-hidden="true" tabindex="-1"></a>X_pred <span class="op">=</span> np.column_stack([</span>
<span id="cb1-285"><a href="#cb1-285" aria-hidden="true" tabindex="-1"></a>    np.full(<span class="dv">200</span>, np.mean(X_gam[:,<span class="dv">0</span>])), x_range,</span>
<span id="cb1-286"><a href="#cb1-286" aria-hidden="true" tabindex="-1"></a>    np.zeros(<span class="dv">200</span>), np.full(<span class="dv">200</span>, <span class="dv">6</span>)</span>
<span id="cb1-287"><a href="#cb1-287" aria-hidden="true" tabindex="-1"></a>])</span>
<span id="cb1-288"><a href="#cb1-288" aria-hidden="true" tabindex="-1"></a>pdep, confi <span class="op">=</span> gam.partial_dependence(term<span class="op">=</span><span class="dv">1</span>, X<span class="op">=</span>X_pred, width<span class="op">=</span><span class="fl">0.95</span>)</span>
<span id="cb1-289"><a href="#cb1-289" aria-hidden="true" tabindex="-1"></a>df_temp_gam <span class="op">=</span> pd.DataFrame({<span class="st">'x'</span>: x_range, <span class="st">'y'</span>: pdep,</span>
<span id="cb1-290"><a href="#cb1-290" aria-hidden="true" tabindex="-1"></a>                              <span class="st">'lower'</span>: confi[:,<span class="dv">0</span>], <span class="st">'upper'</span>: confi[:,<span class="dv">1</span>]})</span>
<span id="cb1-291"><a href="#cb1-291" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-292"><a href="#cb1-292" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-295"><a href="#cb1-295" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb1-296"><a href="#cb1-296" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: fig-gam</span></span>
<span id="cb1-297"><a href="#cb1-297" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-cap: "**Figure 1.** GAM partial-dependence smooth for mean daily temperature. The U-shape — predicted delay minimized in 5–20°C and rising at both extremes — is consistent with frozen track switches in winter and rail thermal expansion in summer."</span></span>
<span id="cb1-298"><a href="#cb1-298" aria-hidden="true" tabindex="-1"></a><span class="co">#| output: true</span></span>
<span id="cb1-299"><a href="#cb1-299" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-300"><a href="#cb1-300" aria-hidden="true" tabindex="-1"></a>p1 <span class="op">=</span> (</span>
<span id="cb1-301"><a href="#cb1-301" aria-hidden="true" tabindex="-1"></a>    ggplot(df_temp_gam, aes(x<span class="op">=</span><span class="st">'x'</span>, y<span class="op">=</span><span class="st">'y'</span>))</span>
<span id="cb1-302"><a href="#cb1-302" aria-hidden="true" tabindex="-1"></a>    <span class="op">+</span> geom_ribbon(aes(ymin<span class="op">=</span><span class="st">'lower'</span>, ymax<span class="op">=</span><span class="st">'upper'</span>), fill<span class="op">=</span><span class="st">'#d73027'</span>, alpha<span class="op">=</span><span class="fl">0.15</span>)</span>
<span id="cb1-303"><a href="#cb1-303" aria-hidden="true" tabindex="-1"></a>    <span class="op">+</span> geom_line(color<span class="op">=</span><span class="st">'#d73027'</span>, size<span class="op">=</span><span class="fl">1.2</span>)</span>
<span id="cb1-304"><a href="#cb1-304" aria-hidden="true" tabindex="-1"></a>    <span class="op">+</span> geom_vline(xintercept<span class="op">=</span><span class="dv">0</span>, linetype<span class="op">=</span><span class="st">'dotted'</span>, color<span class="op">=</span><span class="st">'navy'</span>, size<span class="op">=</span><span class="fl">0.7</span>)</span>
<span id="cb1-305"><a href="#cb1-305" aria-hidden="true" tabindex="-1"></a>    <span class="op">+</span> labs(title<span class="op">=</span><span class="st">'GAM Smooth — Temperature Effect on Delay'</span>,</span>
<span id="cb1-306"><a href="#cb1-306" aria-hidden="true" tabindex="-1"></a>           x<span class="op">=</span><span class="st">'Mean temperature (°C)'</span>, y<span class="op">=</span><span class="st">'Partial effect (min)'</span>)</span>
<span id="cb1-307"><a href="#cb1-307" aria-hidden="true" tabindex="-1"></a>    <span class="op">+</span> theme_minimal()</span>
<span id="cb1-308"><a href="#cb1-308" aria-hidden="true" tabindex="-1"></a>    <span class="op">+</span> theme(figure_size<span class="op">=</span>(<span class="dv">6</span>, <span class="dv">3</span>),</span>
<span id="cb1-309"><a href="#cb1-309" aria-hidden="true" tabindex="-1"></a>            plot_title<span class="op">=</span>element_text(size<span class="op">=</span><span class="dv">10</span>, weight<span class="op">=</span><span class="st">'bold'</span>))</span>
<span id="cb1-310"><a href="#cb1-310" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb1-311"><a href="#cb1-311" aria-hidden="true" tabindex="-1"></a>p1</span>
<span id="cb1-312"><a href="#cb1-312" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-313"><a href="#cb1-313" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-314"><a href="#cb1-314" aria-hidden="true" tabindex="-1"></a>The GAM (pseudo-R² = <span class="in">`{python} f"{gam_r2:.3f}"`</span>) **rejects H₁₀**. Two non-linearities OLS cannot capture: (a) **temperature is U-shaped** (Figure 1); (b) the precipitation smooth saturates near ~10 mm — its right-edge downturn beyond ~15 mm is an extrapolation artifact in a sparse data region, not real saturation. Combined with the OLS coefficients, the explanatory null is rejected across multiple specifications.</span>
<span id="cb1-315"><a href="#cb1-315" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-316"><a href="#cb1-316" aria-hidden="true" tabindex="-1"></a><span class="fu">## H₂ — Predictive Models</span></span>
<span id="cb1-317"><a href="#cb1-317" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-320"><a href="#cb1-320" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb1-321"><a href="#cb1-321" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: ml-prep</span></span>
<span id="cb1-322"><a href="#cb1-322" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-323"><a href="#cb1-323" aria-hidden="true" tabindex="-1"></a>ml_features <span class="op">=</span> [<span class="st">'precip_mm'</span>,<span class="st">'snowfall_cm'</span>,<span class="st">'precip_hours'</span>,<span class="st">'precip_intensity'</span>,</span>
<span id="cb1-324"><a href="#cb1-324" aria-hidden="true" tabindex="-1"></a>               <span class="st">'temp_max'</span>,<span class="st">'temp_min'</span>,<span class="st">'mean_temp_c'</span>,<span class="st">'temp_range'</span>,</span>
<span id="cb1-325"><a href="#cb1-325" aria-hidden="true" tabindex="-1"></a>               <span class="st">'gust_speed'</span>,<span class="st">'is_weekend'</span>,<span class="st">'month_num'</span>,<span class="st">'dow_num'</span>]</span>
<span id="cb1-326"><a href="#cb1-326" aria-hidden="true" tabindex="-1"></a>split_date <span class="op">=</span> pd.Timestamp(<span class="st">'2024-01-01'</span>)</span>
<span id="cb1-327"><a href="#cb1-327" aria-hidden="true" tabindex="-1"></a>df_train <span class="op">=</span> df_merged[df_merged[<span class="st">'date'</span>]<span class="op">&lt;</span>split_date]</span>
<span id="cb1-328"><a href="#cb1-328" aria-hidden="true" tabindex="-1"></a>df_test  <span class="op">=</span> df_merged[df_merged[<span class="st">'date'</span>]<span class="op">&gt;=</span>split_date]</span>
<span id="cb1-329"><a href="#cb1-329" aria-hidden="true" tabindex="-1"></a>X_train, X_test <span class="op">=</span> df_train[ml_features].values, df_test[ml_features].values</span>
<span id="cb1-330"><a href="#cb1-330" aria-hidden="true" tabindex="-1"></a>y_tr_reg, y_te_reg <span class="op">=</span> df_train[<span class="st">'delay_anomaly'</span>].values, df_test[<span class="st">'delay_anomaly'</span>].values</span>
<span id="cb1-331"><a href="#cb1-331" aria-hidden="true" tabindex="-1"></a>y_tr_clf, y_te_clf <span class="op">=</span> df_train[<span class="st">'is_severe'</span>].values, df_test[<span class="st">'is_severe'</span>].values</span>
<span id="cb1-332"><a href="#cb1-332" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-333"><a href="#cb1-333" aria-hidden="true" tabindex="-1"></a>lr_reg  <span class="op">=</span> LinearRegression().fit(X_train, y_tr_reg)</span>
<span id="cb1-334"><a href="#cb1-334" aria-hidden="true" tabindex="-1"></a>rf_reg  <span class="op">=</span> RandomForestRegressor(n_estimators<span class="op">=</span><span class="dv">300</span>, max_depth<span class="op">=</span><span class="dv">8</span>, min_samples_leaf<span class="op">=</span><span class="dv">10</span>,</span>
<span id="cb1-335"><a href="#cb1-335" aria-hidden="true" tabindex="-1"></a>                                 random_state<span class="op">=</span><span class="dv">42</span>, n_jobs<span class="op">=-</span><span class="dv">1</span>).fit(X_train, y_tr_reg)</span>
<span id="cb1-336"><a href="#cb1-336" aria-hidden="true" tabindex="-1"></a>xgb_reg <span class="op">=</span> xgb.XGBRegressor(n_estimators<span class="op">=</span><span class="dv">400</span>, max_depth<span class="op">=</span><span class="dv">6</span>, learning_rate<span class="op">=</span><span class="fl">0.05</span>,</span>
<span id="cb1-337"><a href="#cb1-337" aria-hidden="true" tabindex="-1"></a>                            subsample<span class="op">=</span><span class="fl">0.8</span>, colsample_bytree<span class="op">=</span><span class="fl">0.8</span>,</span>
<span id="cb1-338"><a href="#cb1-338" aria-hidden="true" tabindex="-1"></a>                            random_state<span class="op">=</span><span class="dv">42</span>, n_jobs<span class="op">=-</span><span class="dv">1</span>, verbosity<span class="op">=</span><span class="dv">0</span>).fit(X_train, y_tr_reg)</span>
<span id="cb1-339"><a href="#cb1-339" aria-hidden="true" tabindex="-1"></a>naive_pred <span class="op">=</span> np.full_like(y_te_reg, y_tr_reg.mean(), dtype<span class="op">=</span><span class="bu">float</span>)</span>
<span id="cb1-340"><a href="#cb1-340" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-341"><a href="#cb1-341" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-344"><a href="#cb1-344" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb1-345"><a href="#cb1-345" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: tbl-reg</span></span>
<span id="cb1-346"><a href="#cb1-346" aria-hidden="true" tabindex="-1"></a><span class="co">#| output: true</span></span>
<span id="cb1-347"><a href="#cb1-347" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-348"><a href="#cb1-348" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> reg_m(y_t,y_p):</span>
<span id="cb1-349"><a href="#cb1-349" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> {<span class="st">'RMSE'</span>:np.sqrt(mean_squared_error(y_t,y_p)),</span>
<span id="cb1-350"><a href="#cb1-350" aria-hidden="true" tabindex="-1"></a>            <span class="st">'MAE'</span>:mean_absolute_error(y_t,y_p), <span class="st">'R²'</span>:r2_score(y_t,y_p)}</span>
<span id="cb1-351"><a href="#cb1-351" aria-hidden="true" tabindex="-1"></a>reg_results <span class="op">=</span> pd.DataFrame({</span>
<span id="cb1-352"><a href="#cb1-352" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Naive (mean)'</span>:      reg_m(y_te_reg, naive_pred),</span>
<span id="cb1-353"><a href="#cb1-353" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Linear Regression'</span>: reg_m(y_te_reg, lr_reg.predict(X_test)),</span>
<span id="cb1-354"><a href="#cb1-354" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Random Forest'</span>:     reg_m(y_te_reg, rf_reg.predict(X_test)),</span>
<span id="cb1-355"><a href="#cb1-355" aria-hidden="true" tabindex="-1"></a>    <span class="st">'XGBoost'</span>:           reg_m(y_te_reg, xgb_reg.predict(X_test)),</span>
<span id="cb1-356"><a href="#cb1-356" aria-hidden="true" tabindex="-1"></a>}).T.<span class="bu">round</span>(<span class="dv">3</span>)</span>
<span id="cb1-357"><a href="#cb1-357" aria-hidden="true" tabindex="-1"></a>ipy_display(Markdown(</span>
<span id="cb1-358"><a href="#cb1-358" aria-hidden="true" tabindex="-1"></a>    <span class="st">"**Table 4.** Out-of-sample regression performance on the detrended target "</span></span>
<span id="cb1-359"><a href="#cb1-359" aria-hidden="true" tabindex="-1"></a>    <span class="st">"(`delay_anomaly`), test 2024–2025. RMSE/MAE in min.</span><span class="ch">\n\n</span><span class="st">"</span> <span class="op">+</span> reg_results.to_markdown()))</span>
<span id="cb1-360"><a href="#cb1-360" aria-hidden="true" tabindex="-1"></a>xgb_rmse <span class="op">=</span> reg_results.loc[<span class="st">'XGBoost'</span>,<span class="st">'RMSE'</span>]</span>
<span id="cb1-361"><a href="#cb1-361" aria-hidden="true" tabindex="-1"></a>xgb_r2   <span class="op">=</span> reg_results.loc[<span class="st">'XGBoost'</span>,<span class="st">'R²'</span>]</span>
<span id="cb1-362"><a href="#cb1-362" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-363"><a href="#cb1-363" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-366"><a href="#cb1-366" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb1-367"><a href="#cb1-367" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: tbl-clf</span></span>
<span id="cb1-368"><a href="#cb1-368" aria-hidden="true" tabindex="-1"></a><span class="co">#| output: true</span></span>
<span id="cb1-369"><a href="#cb1-369" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-370"><a href="#cb1-370" aria-hidden="true" tabindex="-1"></a>scaler <span class="op">=</span> StandardScaler()</span>
<span id="cb1-371"><a href="#cb1-371" aria-hidden="true" tabindex="-1"></a>X_tr_s, X_te_s <span class="op">=</span> scaler.fit_transform(X_train), scaler.transform(X_test)</span>
<span id="cb1-372"><a href="#cb1-372" aria-hidden="true" tabindex="-1"></a>lr_clf  <span class="op">=</span> LogisticRegression(max_iter<span class="op">=</span><span class="dv">2000</span>, random_state<span class="op">=</span><span class="dv">42</span>).fit(X_tr_s, y_tr_clf)</span>
<span id="cb1-373"><a href="#cb1-373" aria-hidden="true" tabindex="-1"></a>rf_clf  <span class="op">=</span> RandomForestClassifier(n_estimators<span class="op">=</span><span class="dv">400</span>, max_depth<span class="op">=</span><span class="dv">10</span>, min_samples_leaf<span class="op">=</span><span class="dv">5</span>,</span>
<span id="cb1-374"><a href="#cb1-374" aria-hidden="true" tabindex="-1"></a>                                   random_state<span class="op">=</span><span class="dv">42</span>, n_jobs<span class="op">=-</span><span class="dv">1</span>).fit(X_train, y_tr_clf)</span>
<span id="cb1-375"><a href="#cb1-375" aria-hidden="true" tabindex="-1"></a>xgb_clf <span class="op">=</span> xgb.XGBClassifier(n_estimators<span class="op">=</span><span class="dv">400</span>, max_depth<span class="op">=</span><span class="dv">6</span>, learning_rate<span class="op">=</span><span class="fl">0.05</span>,</span>
<span id="cb1-376"><a href="#cb1-376" aria-hidden="true" tabindex="-1"></a>                              subsample<span class="op">=</span><span class="fl">0.8</span>, colsample_bytree<span class="op">=</span><span class="fl">0.8</span>, eval_metric<span class="op">=</span><span class="st">'logloss'</span>,</span>
<span id="cb1-377"><a href="#cb1-377" aria-hidden="true" tabindex="-1"></a>                              random_state<span class="op">=</span><span class="dv">42</span>, n_jobs<span class="op">=-</span><span class="dv">1</span>, verbosity<span class="op">=</span><span class="dv">0</span>).fit(X_train, y_tr_clf)</span>
<span id="cb1-378"><a href="#cb1-378" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-379"><a href="#cb1-379" aria-hidden="true" tabindex="-1"></a>lr_proba  <span class="op">=</span> lr_clf.predict_proba(X_te_s)[:,<span class="dv">1</span>]</span>
<span id="cb1-380"><a href="#cb1-380" aria-hidden="true" tabindex="-1"></a>rf_proba  <span class="op">=</span> rf_clf.predict_proba(X_test)[:,<span class="dv">1</span>]</span>
<span id="cb1-381"><a href="#cb1-381" aria-hidden="true" tabindex="-1"></a>xgb_proba <span class="op">=</span> xgb_clf.predict_proba(X_test)[:,<span class="dv">1</span>]</span>
<span id="cb1-382"><a href="#cb1-382" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-383"><a href="#cb1-383" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> clf_m(y_t,y_p,y_pr):</span>
<span id="cb1-384"><a href="#cb1-384" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> {<span class="st">'Accuracy'</span>:accuracy_score(y_t,y_p),</span>
<span id="cb1-385"><a href="#cb1-385" aria-hidden="true" tabindex="-1"></a>            <span class="st">'Precision'</span>:precision_score(y_t,y_p,zero_division<span class="op">=</span><span class="dv">0</span>),</span>
<span id="cb1-386"><a href="#cb1-386" aria-hidden="true" tabindex="-1"></a>            <span class="st">'Recall'</span>:recall_score(y_t,y_p,zero_division<span class="op">=</span><span class="dv">0</span>),</span>
<span id="cb1-387"><a href="#cb1-387" aria-hidden="true" tabindex="-1"></a>            <span class="st">'F1'</span>:f1_score(y_t,y_p,zero_division<span class="op">=</span><span class="dv">0</span>),</span>
<span id="cb1-388"><a href="#cb1-388" aria-hidden="true" tabindex="-1"></a>            <span class="st">'ROC-AUC'</span>:roc_auc_score(y_t,y_pr)}</span>
<span id="cb1-389"><a href="#cb1-389" aria-hidden="true" tabindex="-1"></a>clf_results <span class="op">=</span> pd.DataFrame({</span>
<span id="cb1-390"><a href="#cb1-390" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Logistic Regression'</span>: clf_m(y_te_clf, (lr_proba<span class="op">&gt;=</span><span class="fl">0.5</span>).astype(<span class="bu">int</span>), lr_proba),</span>
<span id="cb1-391"><a href="#cb1-391" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Random Forest'</span>:       clf_m(y_te_clf, (rf_proba<span class="op">&gt;=</span><span class="fl">0.5</span>).astype(<span class="bu">int</span>), rf_proba),</span>
<span id="cb1-392"><a href="#cb1-392" aria-hidden="true" tabindex="-1"></a>    <span class="st">'XGBoost'</span>:             clf_m(y_te_clf, (xgb_proba<span class="op">&gt;=</span><span class="fl">0.5</span>).astype(<span class="bu">int</span>), xgb_proba),</span>
<span id="cb1-393"><a href="#cb1-393" aria-hidden="true" tabindex="-1"></a>}).T.<span class="bu">round</span>(<span class="dv">3</span>)</span>
<span id="cb1-394"><a href="#cb1-394" aria-hidden="true" tabindex="-1"></a>ipy_display(Markdown(</span>
<span id="cb1-395"><a href="#cb1-395" aria-hidden="true" tabindex="-1"></a>    <span class="st">"**Table 5.** Out-of-sample classification performance, test 2024–2025. "</span></span>
<span id="cb1-396"><a href="#cb1-396" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Severe = top-quartile detrended anomaly.</span><span class="ch">\n\n</span><span class="st">"</span> <span class="op">+</span> clf_results.to_markdown()))</span>
<span id="cb1-397"><a href="#cb1-397" aria-hidden="true" tabindex="-1"></a>xgb_auc <span class="op">=</span> clf_results.loc[<span class="st">'XGBoost'</span>,<span class="st">'ROC-AUC'</span>]</span>
<span id="cb1-398"><a href="#cb1-398" aria-hidden="true" tabindex="-1"></a>rf_auc  <span class="op">=</span> clf_results.loc[<span class="st">'Random Forest'</span>,<span class="st">'ROC-AUC'</span>]</span>
<span id="cb1-399"><a href="#cb1-399" aria-hidden="true" tabindex="-1"></a>lr_auc  <span class="op">=</span> clf_results.loc[<span class="st">'Logistic Regression'</span>,<span class="st">'ROC-AUC'</span>]</span>
<span id="cb1-400"><a href="#cb1-400" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-401"><a href="#cb1-401" aria-hidden="true" tabindex="-1"></a><span class="co"># Sensitivity at p90</span></span>
<span id="cb1-402"><a href="#cb1-402" aria-hidden="true" tabindex="-1"></a>anomaly_q90 <span class="op">=</span> df_merged.loc[train_mask, <span class="st">'delay_anomaly'</span>].quantile(<span class="fl">0.90</span>)</span>
<span id="cb1-403"><a href="#cb1-403" aria-hidden="true" tabindex="-1"></a>df_merged[<span class="st">'is_severe_p90'</span>] <span class="op">=</span> (df_merged[<span class="st">'delay_anomaly'</span>]<span class="op">&gt;=</span>anomaly_q90).astype(<span class="bu">int</span>)</span>
<span id="cb1-404"><a href="#cb1-404" aria-hidden="true" tabindex="-1"></a>y_tr_p90 <span class="op">=</span> df_merged.loc[df_merged[<span class="st">'date'</span>]<span class="op">&lt;</span>split_date,<span class="st">'is_severe_p90'</span>].values</span>
<span id="cb1-405"><a href="#cb1-405" aria-hidden="true" tabindex="-1"></a>y_te_p90 <span class="op">=</span> df_merged.loc[df_merged[<span class="st">'date'</span>]<span class="op">&gt;=</span>split_date,<span class="st">'is_severe_p90'</span>].values</span>
<span id="cb1-406"><a href="#cb1-406" aria-hidden="true" tabindex="-1"></a>xgb_p90 <span class="op">=</span> xgb.XGBClassifier(n_estimators<span class="op">=</span><span class="dv">400</span>, max_depth<span class="op">=</span><span class="dv">6</span>, learning_rate<span class="op">=</span><span class="fl">0.05</span>,</span>
<span id="cb1-407"><a href="#cb1-407" aria-hidden="true" tabindex="-1"></a>                              subsample<span class="op">=</span><span class="fl">0.8</span>, colsample_bytree<span class="op">=</span><span class="fl">0.8</span>,</span>
<span id="cb1-408"><a href="#cb1-408" aria-hidden="true" tabindex="-1"></a>                              random_state<span class="op">=</span><span class="dv">42</span>, n_jobs<span class="op">=-</span><span class="dv">1</span>, verbosity<span class="op">=</span><span class="dv">0</span>).fit(X_train, y_tr_p90)</span>
<span id="cb1-409"><a href="#cb1-409" aria-hidden="true" tabindex="-1"></a>xgb_p90_auc <span class="op">=</span> roc_auc_score(y_te_p90, xgb_p90.predict_proba(X_test)[:,<span class="dv">1</span>])</span>
<span id="cb1-410"><a href="#cb1-410" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-411"><a href="#cb1-411" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-414"><a href="#cb1-414" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb1-415"><a href="#cb1-415" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: fig-roc</span></span>
<span id="cb1-416"><a href="#cb1-416" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-cap: "**Figure 2.** ROC curves on the held-out 2024–2025 test set, predicting top-quartile severe delay days. The dashed diagonal is the no-information baseline (AUC = 0.5)."</span></span>
<span id="cb1-417"><a href="#cb1-417" aria-hidden="true" tabindex="-1"></a><span class="co">#| output: true</span></span>
<span id="cb1-418"><a href="#cb1-418" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-419"><a href="#cb1-419" aria-hidden="true" tabindex="-1"></a>fpr_lr,tpr_lr,_ <span class="op">=</span> roc_curve(y_te_clf, lr_proba)</span>
<span id="cb1-420"><a href="#cb1-420" aria-hidden="true" tabindex="-1"></a>fpr_rf,tpr_rf,_ <span class="op">=</span> roc_curve(y_te_clf, rf_proba)</span>
<span id="cb1-421"><a href="#cb1-421" aria-hidden="true" tabindex="-1"></a>fpr_xg,tpr_xg,_ <span class="op">=</span> roc_curve(y_te_clf, xgb_proba)</span>
<span id="cb1-422"><a href="#cb1-422" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">5</span>, <span class="dv">4</span>))</span>
<span id="cb1-423"><a href="#cb1-423" aria-hidden="true" tabindex="-1"></a>ax.plot(fpr_lr,tpr_lr, color<span class="op">=</span><span class="st">'#1a9641'</span>, linewidth<span class="op">=</span><span class="fl">1.8</span>, label<span class="op">=</span><span class="ss">f'Logistic Reg (AUC=</span><span class="sc">{</span>lr_auc<span class="sc">:.3f}</span><span class="ss">)'</span>)</span>
<span id="cb1-424"><a href="#cb1-424" aria-hidden="true" tabindex="-1"></a>ax.plot(fpr_rf,tpr_rf, color<span class="op">=</span><span class="st">'#fdae61'</span>, linewidth<span class="op">=</span><span class="fl">1.8</span>, label<span class="op">=</span><span class="ss">f'Random Forest (AUC=</span><span class="sc">{</span>rf_auc<span class="sc">:.3f}</span><span class="ss">)'</span>)</span>
<span id="cb1-425"><a href="#cb1-425" aria-hidden="true" tabindex="-1"></a>ax.plot(fpr_xg,tpr_xg, color<span class="op">=</span><span class="st">'#d7191c'</span>, linewidth<span class="op">=</span><span class="fl">2.2</span>, label<span class="op">=</span><span class="ss">f'XGBoost (AUC=</span><span class="sc">{</span>xgb_auc<span class="sc">:.3f}</span><span class="ss">)'</span>)</span>
<span id="cb1-426"><a href="#cb1-426" aria-hidden="true" tabindex="-1"></a>ax.plot([<span class="dv">0</span>,<span class="dv">1</span>],[<span class="dv">0</span>,<span class="dv">1</span>], color<span class="op">=</span><span class="st">'gray'</span>, linestyle<span class="op">=</span><span class="st">'--'</span>, linewidth<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb1-427"><a href="#cb1-427" aria-hidden="true" tabindex="-1"></a>ax.set_xlabel(<span class="st">'False positive rate'</span>)<span class="op">;</span> ax.set_ylabel(<span class="st">'True positive rate'</span>)</span>
<span id="cb1-428"><a href="#cb1-428" aria-hidden="true" tabindex="-1"></a>ax.set_title(<span class="st">'ROC — Severe Delay Day Classification'</span>, fontsize<span class="op">=</span><span class="dv">10</span>, fontweight<span class="op">=</span><span class="st">'bold'</span>)</span>
<span id="cb1-429"><a href="#cb1-429" aria-hidden="true" tabindex="-1"></a>ax.legend(loc<span class="op">=</span><span class="st">'lower right'</span>, frameon<span class="op">=</span><span class="va">True</span>, fontsize<span class="op">=</span><span class="dv">8</span>)</span>
<span id="cb1-430"><a href="#cb1-430" aria-hidden="true" tabindex="-1"></a>ax.grid(alpha<span class="op">=</span><span class="fl">0.3</span>)<span class="op">;</span> ax.set_xlim(<span class="dv">0</span>,<span class="dv">1</span>)<span class="op">;</span> ax.set_ylim(<span class="dv">0</span>,<span class="fl">1.02</span>)</span>
<span id="cb1-431"><a href="#cb1-431" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb1-432"><a href="#cb1-432" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb1-433"><a href="#cb1-433" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-434"><a href="#cb1-434" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-437"><a href="#cb1-437" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb1-438"><a href="#cb1-438" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: fig-fi</span></span>
<span id="cb1-439"><a href="#cb1-439" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-cap: "**Figure 3.** XGBoost regressor feature importance (gain). Top three (red): snowfall, mean temperature, day-of-week — matching the predictors flagged as most consequential by OLS and GAM."</span></span>
<span id="cb1-440"><a href="#cb1-440" aria-hidden="true" tabindex="-1"></a><span class="co">#| output: true</span></span>
<span id="cb1-441"><a href="#cb1-441" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-442"><a href="#cb1-442" aria-hidden="true" tabindex="-1"></a>fi_df <span class="op">=</span> pd.DataFrame({<span class="st">'feature'</span>:ml_features,<span class="st">'importance'</span>:xgb_reg.feature_importances_}</span>
<span id="cb1-443"><a href="#cb1-443" aria-hidden="true" tabindex="-1"></a>                     ).sort_values(<span class="st">'importance'</span>, ascending<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb1-444"><a href="#cb1-444" aria-hidden="true" tabindex="-1"></a>top3_set <span class="op">=</span> <span class="bu">set</span>(fi_df.tail(<span class="dv">3</span>)[<span class="st">'feature'</span>])</span>
<span id="cb1-445"><a href="#cb1-445" aria-hidden="true" tabindex="-1"></a>colors_bar <span class="op">=</span> [<span class="st">'#d7191c'</span> <span class="cf">if</span> f <span class="kw">in</span> top3_set <span class="cf">else</span> <span class="st">'#abd9e9'</span> <span class="cf">for</span> f <span class="kw">in</span> fi_df[<span class="st">'feature'</span>]]</span>
<span id="cb1-446"><a href="#cb1-446" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="fl">6.5</span>, <span class="fl">3.5</span>))</span>
<span id="cb1-447"><a href="#cb1-447" aria-hidden="true" tabindex="-1"></a>ax.barh(fi_df[<span class="st">'feature'</span>], fi_df[<span class="st">'importance'</span>], color<span class="op">=</span>colors_bar)</span>
<span id="cb1-448"><a href="#cb1-448" aria-hidden="true" tabindex="-1"></a>ax.set_xlabel(<span class="st">'Feature importance (gain)'</span>)</span>
<span id="cb1-449"><a href="#cb1-449" aria-hidden="true" tabindex="-1"></a>ax.set_title(<span class="st">'XGBoost Feature Importance'</span>, fontsize<span class="op">=</span><span class="dv">10</span>, fontweight<span class="op">=</span><span class="st">'bold'</span>)</span>
<span id="cb1-450"><a href="#cb1-450" aria-hidden="true" tabindex="-1"></a>ax.spines[[<span class="st">'top'</span>,<span class="st">'right'</span>]].set_visible(<span class="va">False</span>)</span>
<span id="cb1-451"><a href="#cb1-451" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb1-452"><a href="#cb1-452" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb1-453"><a href="#cb1-453" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-454"><a href="#cb1-454" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-455"><a href="#cb1-455" aria-hidden="true" tabindex="-1"></a>After detrending, **XGBoost achieves the best out-of-sample performance** for both tasks (regression: RMSE = `{python} f"{xgb_rmse:.1f}"` min, R² = `{python} f"{xgb_r2:.3f}"`; classification: ROC-AUC = `{python} f"{xgb_auc:.3f}"`). Random Forest is close behind; linear models lag substantially. All three classifiers clear the 0.5 baseline, so **H₂₀ is rejected**. The 90th-percentile sensitivity check yields a comparable XGBoost AUC of `{python} f"{xgb_p90_auc:.3f}"`, confirming robustness to the cutoff choice. The R² is modest in absolute terms, as expected — most large single-day delays are caused by random non-weather events (signal failures, security incidents) unforecastable from weather alone. The **top three features by gain — snowfall, mean temperature, day-of-week** (Figure 3) — match the OLS and GAM findings, providing convergent evidence across linear, spline-based, and tree-based model classes.</span>
<span id="cb1-456"><a href="#cb1-456" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-457"><a href="#cb1-457" aria-hidden="true" tabindex="-1"></a><span class="fu"># Conclusions and Summary</span></span>
<span id="cb1-458"><a href="#cb1-458" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-459"><a href="#cb1-459" aria-hidden="true" tabindex="-1"></a>**H₁ — Explanatory (rejected the null).** OLS finds precipitation (β ≈ 1.2 min/mm, p &lt; 0.001) and snowfall (β ≈ 14 min/cm, p &lt; 0.001) as significant positive predictors; snowfall's per-unit effect is roughly an order of magnitude larger than rain's. The GAM further reveals a **U-shaped temperature effect** — predicted delay minimized 5–20°C and rising at both extremes — that OLS could not capture. The weekend indicator is strongly negative (β ≈ −32 min, p &lt; 0.001).</span>
<span id="cb1-460"><a href="#cb1-460" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-461"><a href="#cb1-461" aria-hidden="true" tabindex="-1"></a>**H₂ — Predictive (rejected the null).** After detrending the target to remove the post-2021 baseline rise, **XGBoost achieves the best out-of-sample performance** for both regression (RMSE ≈ `{python} f"{xgb_rmse:.0f}"` min, R² ≈ `{python} f"{xgb_r2:.2f}"`) and classification (ROC-AUC ≈ `{python} f"{xgb_auc:.2f}"`). All three models clear the no-information baselines, and the 90th-percentile sensitivity check confirms the conclusion does not depend on the cutoff. Most importantly, the **top three features by gain — snowfall, mean temperature, day-of-week** — match the predictors that OLS and GAM identified as most consequential, demonstrating convergence between explanatory and predictive analyses across very different model classes.</span>
<span id="cb1-462"><a href="#cb1-462" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-463"><a href="#cb1-463" aria-hidden="true" tabindex="-1"></a><span class="fu">## Note on Detrending and Distribution Shift</span></span>
<span id="cb1-464"><a href="#cb1-464" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-465"><a href="#cb1-465" aria-hidden="true" tabindex="-1"></a>A direct prediction of <span class="in">`total_delay_mins`</span> produces *negative* out-of-sample R² for all three models — not because weather lacks predictive signal, but because the test-period mean total delay (~200 min) is far above the training-period mean (~140 min), so any model anchored to the training distribution systematically under-predicts. By predicting <span class="in">`delay_anomaly`</span> (each day's deviation from its calendar-month mean) we remove this baseline drift and isolate the weather-driven component. This is the methodologically appropriate approach when the target series is non-stationary, as is the case for TTC delays after 2021.</span>
<span id="cb1-466"><a href="#cb1-466" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-467"><a href="#cb1-467" aria-hidden="true" tabindex="-1"></a><span class="fu">## Limitations</span></span>
<span id="cb1-468"><a href="#cb1-468" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-469"><a href="#cb1-469" aria-hidden="true" tabindex="-1"></a>(1) **Weather explains a modest fraction of variance.** Even after detrending, XGBoost achieves only R² ≈ `{python} f"{xgb_r2:.2f}"`. Most day-to-day variation in delay anomalies is driven by non-weather factors (equipment failures, security incidents, passenger emergencies) the data do not capture. Operational data (rolling-stock age, ridership) at daily granularity would likely improve performance but is not publicly available. (2) **Aggregation hides line-level heterogeneity.** Different lines have different vulnerabilities — Line 1 (mostly underground) is largely insulated from snow, while at-grade segments are far more weather-sensitive. Line/station disaggregation is a natural next step. (3) **Production deployment requires re-training.** The post-2021 baseline rise documented here means a model trained on historical data cannot be deployed indefinitely; annual or quarterly re-training would be needed to track the drifting baseline.</span>
</code></pre></div><button title="Copy to Clipboard" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></div>
</div></div></div></div></div>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>JSC370 Final Project — Xiran Yin (2026)</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
<p>Built with Quarto</p>
</div>
  </div>
</footer>




</body></html>